## Array Creation in SciPy.


- In SciPy, arrays are created using NumPy, which is the core package for numerical computing in Python and SciPy is built on top of NumPy and uses NumPy Arrays (ndarray) as its core Data Structure.


- Array creation refers to the process of initializing arrays—1D, 2D, 3D, or higher dimensions—with specific data or rules (e.g., all zeros, a range of numbers, random values).

- Arrays are used for performing efficient numerical operations on datasets—e.g., linear algebra, calculus, simulations, machine learning, etc.

- You can create 1D, 2D, 3D, and n-dimensional arrays depending on your data requirements.

- SciPy (via NumPy) supports multiple functions for creating arrays: array(), arange(), zeros(), ones(), empty(), linspace(), full(), eye(), random functions, etc.

- Every array has a shape (e.g., (3, 4)) and a dimension (ndim), which determine its structure and how you can operate on it.

- Arrays can store data in different types: int, float, bool, complex, etc.  and you can specify data types using dtype.

- Arrays enable fast, vectorized computations (as opposed to slow Python loops).

- Functions like zeros(), empty(), and full() are useful to allocate memory and fill later.

- Functions like np.random.rand() and np.random.randint() help generate random data for simulations or testing algorithms.

- After creation, arrays can be reshaped, indexed, or sliced for further manipulation.

- All core SciPy functions like scipy.linalg, scipy.optimize, etc., accept NumPy arrays—so array creation is the first step in using SciPy effectively.





## 1D Array in SciPy.


- A 1D Array is a Single Row or Linear Array of Elements and It's the most Basic Type of Array in SciPy/NumPy.

-  SciPy uses NumPy arrays (ndarray) as its core data structure and so, creating arrays in SciPy is essentially the same as using NumPy.

-  All elements in a 1D array are stored in contiguous memory blocks for fast access.

-  Created using np.array(), np.arange(), np.zeros(), np.ones(), np.linspace(), etc.

-  A 1D Array generally contains elements of the same data type, like integers or floats.

-  Its ndim is 1 and shape is (n,), where n is the number of elements.

-  You can perform operations between a 1D array and scalar or other arrays due to NumPy's broadcasting feature.

-  Linear Data Structure   : It contains elements in a single straight line (1-dimensional).

-  Shape and Size    : Shape is (n,), and size gives number of elements.

-  Indexing Support    : Supports positive and negative indexing like Python lists.

-  Data Types   :   Can store floats, ints, bools, strings, etc. with dtype attribute.

-  Slicing     :  Supports slicing: arr[1:4], arr[::-1], etc.

-  Fast Math Operations     :  Operations like arr + 1, arr * 2 are applied element-wise.

-  Memory Efficient       :  Stored in contiguous blocks for fast computation.

-  Broadcasting Compatible        :   Can be combined with scalars and arrays of different shapes.

- Supports Aggregations     :    Functions like sum(), mean(), max(), etc.

- Foundation of Vector Algebra     :  Essential for operations like dot product, norms, etc.



## Different Methods to Create 1D Array in SciPy.

## Creating 1D Array with np.array() -  From List or Tuple.


In [2]:
import numpy as np

arr1 = np.array([10, 20, 30, 40])
print("1D array from list:", arr1)

arr2 = np.array((5, 15, 25))
print("1D array from tuple:", arr2)


1D array from list: [10 20 30 40]
1D array from tuple: [ 5 15 25]


## Creating 1D Array with np.arange() – With range and step.

In [3]:
arr3 = np.arange(0, 10)
print("Using arange (0 to 9):", arr3)

arr4 = np.arange(5, 25, 5)
print("Using arange with step:", arr4)


Using arange (0 to 9): [0 1 2 3 4 5 6 7 8 9]
Using arange with step: [ 5 10 15 20]


## Creating 1D Array with np.linspace() – Even spacing between range.

In [4]:
arr5 = np.linspace(0, 1, 5)
print("Evenly spaced values:", arr5)

arr6 = np.linspace(10, 20, 6)
print("From 10 to 20 in 6 parts:", arr6)


Evenly spaced values: [0.   0.25 0.5  0.75 1.  ]
From 10 to 20 in 6 parts: [10. 12. 14. 16. 18. 20.]


## Creating 1D Array with np.zeros() – All zeros in 1D Array.

In [5]:
arr7 = np.zeros(5)
print("1D array of zeros:", arr7)


1D array of zeros: [0. 0. 0. 0. 0.]


## Creating 1D Array with np.ones() – All ones in 1D Array.

In [6]:
arr8 = np.ones(4)
print("1D array of ones:", arr8)


1D array of ones: [1. 1. 1. 1.]


## Creating 1D Array np.random.rand() – Random float values between 0 and 1.

In [7]:
arr10 = np.random.rand(5)
print("Random float values:", arr10)


Random float values: [0.73122445 0.4038801  0.21450516 0.12963014 0.55056216]


## Features of 1D Array.

In [8]:
arr = np.array([10, 20, 30, 40, 50])

# 1. Shape and size
print("Shape:", arr.shape)
print("Size:", arr.size)

# 2. Indexing and Slicing
print("Element at index 2:", arr[2])
print("Sliced array:", arr[1:4])

# 3. Data type
print("Data type:", arr.dtype)

# 4. Arithmetic operation
print("Array multiplied by 2:", arr * 2)

# 5. Broadcasting with scalar
print("Array + 5:", arr + 5)

# 6. Aggregation
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# 7. Mutation
arr[0] = 99
print("After mutation:", arr)


Shape: (5,)
Size: 5
Element at index 2: 30
Sliced array: [20 30 40]
Data type: int32
Array multiplied by 2: [ 20  40  60  80 100]
Array + 5: [15 25 35 45 55]
Sum: 150
Mean: 30.0
After mutation: [99 20 30 40 50]


## 2D Array in SciPy.


- A 2D Array is an array with two dimensions—rows and columns—like a matrix or a spreadsheet and it is created using NumPy, which is the core array library used in SciPy.

- A 2D array can be visualized as a table of elements arranged in m x n format (m rows and n columns).
Example: [[1, 2, 3], [4, 5, 6]] is a 2D array with shape (2, 3).

- SciPy uses NumPy arrays (ndarray) under the hood. So, all 2D arrays in SciPy are created and manipulated using NumPy syntax.

- A 2D array is often used to represent matrices, images, or datasets with rows and columns.

- Indexing in 2D Arrays     : You can access elements using [row, column] format. Example: arr[1][2] or arr[1, 2].

- Shape and Size     :  arr.shape gives dimensions, e.g., (3, 4) for a 3x4 array and  arr.size gives total number of elements.

- np.array(), np.zeros((m, n)), np.ones((m, n)), np.full(), np.eye(), np.random.rand(m, n), etc.

- All elements are of the same data type, e.g., int32, float64.

- Supports matrix operations: addition, multiplication, transpose, dot product, etc.

- Rows, columns, or blocks can be selected using slicing like arr[:, 1] (all rows, column 1).

- arr.shape tells you the number of rows and columns.

- Elements are stored in contiguous memory, allowing fast computation.

- You can access any value with two indices: arr[row, col].

- Supports element-wise operations (+, -, *, /) and supports matrix multiplication, transpose, inverse (via scipy.linalg), etc.

- Works with NumPy/SciPy functions: np.sum(), np.mean(), np.transpose(), etc

- Can Be Initialized in Many Ways : Using np.array(), np.zeros(), np.ones(), np.eye(), np.full(), np.random.rand(), etc.

- Homogeneous Data -  Types :  All Elements share the same dtype (e.g., int32, float64).


## Different Methods to Create 2D Array in SciPy.

## Creating 2D Array Using np.array().

In [9]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])  # 2 rows, 3 columns
print("2D array:\n", arr)


2D array:
 [[1 2 3]
 [4 5 6]]


## Creating 2D Array using np.zeros().

In [10]:
zeros_arr = np.zeros((3, 4))  # 3x4 array of zeros
print("Zeros 2D array:\n", zeros_arr)


Zeros 2D array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Creating 2D Array using np.ones().

In [11]:
ones_arr = np.ones((2, 5))  # 2 rows, 5 columns filled with 1
print("Ones 2D array:\n", ones_arr)


Ones 2D array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Creating  2D Array using np.full().

In [12]:
filled_arr = np.full((3, 3), 7)  # 3x3 matrix filled with 7s
print("Full 2D array:\n", filled_arr)


Full 2D array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


## Creating 2D Array using np.eye() – Identity Matrix.

In [13]:
identity_arr = np.eye(4)  # 4x4 identity matrix
print("Identity matrix:\n", identity_arr)


Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Creating 2D Array using np.random.rand().

In [14]:
random_arr = np.random.rand(2, 3)  # 2x3 array with random floats [0,1)
print("Random 2D array:\n", random_arr)


Random 2D array:
 [[0.63328474 0.32066315 0.85067916]
 [0.31961199 0.65335307 0.50749415]]


## Features of 2D Array.

In [18]:
#1) Create a 2D Array and Check Shape.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)

#2) Indexing and Slicing in 2D Array.
# Access element at row 1, column 2.

print("Element at [1, 2]:", arr[1, 2])  # Output: 6

# Get second row/

print("Second row:", arr[1])  # Output: [4 5 6]

# Get second column.

print("Second column:", arr[:, 1])  # Output: [2 5]

#3) Element-wise Operations.

print("Array multiplied by 2:\n", arr * 2)
print("Array + 5:\n", arr + 5)


#4) Broadcasting 2D Array.

# Add a 1D array (row) to each row of 2D array
row = np.array([10, 20, 30])
print("Broadcasted addition:\n", arr + row)


#5) Matrix Transpose.

print("Transposed array:\n", arr.T)


#6) Using Zeros, Ones, Full.

print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((2, 3)))
print("Full:\n", np.full((2, 3), 7))


#7) Using Identity Matrix.

identity = np.eye(3)
print("3x3 Identity Matrix:\n", identity)


#8) Aggregation Functions in 2D Array.


print("Sum of all elements:", np.sum(arr))
print("Column-wise sum:", np.sum(arr, axis=0))
print("Row-wise mean:", np.mean(arr, axis=1))


#9) Data Type (dtype) in 2D Array.


print("Data type of array:", arr.dtype)









2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Element at [1, 2]: 6
Second row: [4 5 6]
Second column: [2 5]
Array multiplied by 2:
 [[ 2  4  6]
 [ 8 10 12]]
Array + 5:
 [[ 6  7  8]
 [ 9 10 11]]
Broadcasted addition:
 [[11 22 33]
 [14 25 36]]
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full:
 [[7 7 7]
 [7 7 7]]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Sum of all elements: 21
Column-wise sum: [5 7 9]
Row-wise mean: [2. 5.]
Data type of array: int32


## 3D Array in SciPy.


- A 3D Array is an array with three dimensions: depth, rows, and columns.

- It can be thought of as a collection of 2D matrices stacked on top of each other.

- Given by .shape, in the form (depth, rows, columns). Example: np.zeros((3, 4, 5)) → 3 matrices of 4 rows and 5 columns each.

- Indexing: Access elements using 3 indices: [matrix_index, row_index, col_index].

- Homogeneous Data Type: All elements must be of the same dtype.

- Initialization Methods: Can be created using np.array(), np.zeros(), np.ones(), np.random.rand(), etc.

- Operations: Supports element-wise math, broadcasting, reshaping, slicing, and aggregation.

- Manipulation: 3D arrays can be sliced into 2D arrays or reshaped into 1D or 2D as needed.

- Basis for Tensors: 3D arrays are considered rank-3 tensors, important in machine learning and physics.

- Extremely Efficient: Backed by NumPy's high-speed C implementation for fast data manipulation.




## Different Methods to Create 3D Array in SciPy.

## Creating a 3D Array Manually. 

In [19]:
import numpy as np

arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])  # Shape: (2, 2, 2)
print("3D Array:\n", arr_3d)
print("Shape:", arr_3d.shape)


3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


## Creating a 3D Array using np.zeros().

In [20]:
zero_3d = np.zeros((2, 3, 4))  # 2 matrices, 3 rows, 4 columns
print("3D Zeros Array:\n", zero_3d)


3D Zeros Array:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## Creating a 3D Array using np.ones().

In [21]:
ones_3d = np.ones((3, 2, 2))  # 3 matrices of 2x2
print("3D Ones Array:\n", ones_3d)


3D Ones Array:
 [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


## Creating a 3D Array using  np.random.rand().

In [22]:
rand_3d = np.random.rand(2, 2, 3)
print("3D Random Array:\n", rand_3d)


3D Random Array:
 [[[0.45012477 0.10739428 0.66765332]
  [0.87866062 0.90884597 0.65976088]]

 [[0.79748101 0.72800575 0.46293814]
  [0.4972808  0.33499959 0.0469628 ]]]


## Features of 3D Array.

In [28]:
import numpy as np

# Create a 3D array of shape (2, 3, 4).


arr = np.array([
    [[ 1,  2,  3,  4],
     [ 5,  6,  7,  8],
     [ 9, 10, 11, 12]],
    
    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

print("3D Array:\n", arr)

# Shape of 3D Array.


print("Shape:", arr.shape)  # Output: (2, 3, 4)


# Indexing in 3D Array.


#1)  Access a Single Element.
# Access element in 2nd matrix, 3rd row, 4th column (value: 24).
element = arr[1, 2, 3]
print("Element at [1, 2, 3]:", element)


#2)  Access an Entire 2D Slice (Matrix).
# Get the 1st 2D matrix (depth index 0)
matrix1 = arr[0]
print("First 2D Matrix:\n", matrix1)



#3) Access a Single Row from All Matrices.
# Get the second row from all 2D matrices
second_rows = arr[:, 1, :]
print("Second row from all matrices:\n", second_rows)


#4) Access a Single Column from All Matrices.
# Get the third column (index 2) from each Matrix.
third_cols = arr[:, :, 2]
print("Third column from all matrices:\n", third_cols)


#5) Modify an Element.
# Change the element at [0, 1, 2] to 99
arr[0, 1, 2] = 99
print("Modified Array:\n", arr)



3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
Element at [1, 2, 3]: 24
First 2D Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second row from all matrices:
 [[ 5  6  7  8]
 [17 18 19 20]]
Third column from all matrices:
 [[ 3  7 11]
 [15 19 23]]
Modified Array:
 [[[ 1  2  3  4]
  [ 5  6 99  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [25]:
# Element-wise means the operation is applied individually to every pair of elements at the same position in each array.
# 3D arrays have three axes: depth (layers), rows, and columns. Shape: (depth, rows, columns).
# Both arrays must have the same shape, or shapes must be broadcast-compatible.
# Supported operations: +, -, *, /, **, %, and more.
# NumPy automatically broadcasts scalar values across the 3D structure.
# Element-wise arithmetic is highly optimized and memory-efficient in NumPy.
# You can use both operators (+, *) and functions (np.add(), np.multiply()).

import numpy as np

# Create two 3D arrays of shape (2, 2, 3)
arr1 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

arr2 = np.array([
    [[10, 20, 30], [40, 50, 60]],
    [[70, 80, 90], [100, 110, 120]]
])

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)


# Element-wise Addition.
add_result = arr1 + arr2
print("Addition:\n", add_result)



# Element-wise Subtraction.
sub_result = arr2 - arr1
print("Subtraction:\n", sub_result)




# Element-wise Multiplication.
mul_result = arr1 * arr2
print("Multiplication:\n", mul_result)




# Element-wise Division.
div_result = arr2 / arr1
print("Division:\n", div_result)





# Element-wise Exponentiation.
exp_result = arr1 ** 2
print("Exponentiation (arr1 squared):\n", exp_result)





# Modulo Operation.
mod_result = arr2 % arr1
print("Modulo (arr2 % arr1):\n", mod_result)



Array 1:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Array 2:
 [[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
Addition:
 [[[ 11  22  33]
  [ 44  55  66]]

 [[ 77  88  99]
  [110 121 132]]]
Subtraction:
 [[[  9  18  27]
  [ 36  45  54]]

 [[ 63  72  81]
  [ 90  99 108]]]
Multiplication:
 [[[  10   40   90]
  [ 160  250  360]]

 [[ 490  640  810]
  [1000 1210 1440]]]
Division:
 [[[10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]]]
Exponentiation (arr1 squared):
 [[[  1   4   9]
  [ 16  25  36]]

 [[ 49  64  81]
  [100 121 144]]]
Modulo (arr2 % arr1):
 [[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [26]:
# Broadcasting is a powerful feature in NumPy that allows arrays of different shapes to be used together in arithmetic operations by stretching one or both arrays as needed—without making actual copies.
# You have a 3D array of shape (2, 3, 4) and a 2D array of shape (3, 4) — NumPy will automatically broadcast the 2D array to each matrix in the 3D array for operations like addition, subtraction, etc.


# Add 2D Array to 3D Array.
import numpy as np

# 3D array of shape (2, 3, 4)
arr_3d = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],
    
    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

# 2D array of shape (3, 4)
arr_2d = np.array([
    [10, 10, 10, 10],
    [20, 20, 20, 20],
    [30, 30, 30, 30]
])

# Broadcasting addition
result = arr_3d + arr_2d

print("Broadcasted Addition Result:\n", result)


# Subtract 2D from 3D (Broadcasting).
# Subtract arr_2d from each 2D slice in arr_3d
result = arr_3d - arr_2d
print("Broadcasted Subtraction:\n", result)


# Multiply 3D with 2D
# Multiply arr_3d by arr_2d (element-wise broadcast)
result = arr_3d * arr_2d
print("Broadcasted Multiplication:\n", result)


# Divide 3D by 2D (Broadcasting).
# Avoid division by zero in real scenarios
result = arr_3d / arr_2d
print("Broadcasted Division:\n", result)



Broadcasted Addition Result:
 [[[11 12 13 14]
  [25 26 27 28]
  [39 40 41 42]]

 [[23 24 25 26]
  [37 38 39 40]
  [51 52 53 54]]]
Broadcasted Subtraction:
 [[[ -9  -8  -7  -6]
  [-15 -14 -13 -12]
  [-21 -20 -19 -18]]

 [[  3   4   5   6]
  [ -3  -2  -1   0]
  [ -9  -8  -7  -6]]]
Broadcasted Multiplication:
 [[[ 10  20  30  40]
  [100 120 140 160]
  [270 300 330 360]]

 [[130 140 150 160]
  [340 360 380 400]
  [630 660 690 720]]]
Broadcasted Division:
 [[[0.1        0.2        0.3        0.4       ]
  [0.25       0.3        0.35       0.4       ]
  [0.3        0.33333333 0.36666667 0.4       ]]

 [[1.3        1.4        1.5        1.6       ]
  [0.85       0.9        0.95       1.        ]
  [0.7        0.73333333 0.76666667 0.8       ]]]


In [27]:
# Aggregate Operations.

print("Sum of all elements:", np.sum(arr))
print("Mean of all elements:", np.mean(arr))
print("Sum along depth (axis=0):\n", np.sum(arr, axis=0))  # 2D output

Sum of all elements: 392
Mean of all elements: 16.333333333333332
Sum along depth (axis=0):
 [[ 14  16  18  20]
 [ 22  24 118  28]
 [ 30  32  34  36]]
