## Inverse of the Matrix in Scipy.

- The Inverse of a Matrix is like the Reciprocal of a Number. For a Square Matrix A, its Inverse A^-1 is a Matrix that satisfies the Condition  :
A .  A^ - 1  = I,  I is the Identity Matrix (ones on the diagonal and zeros elsewhere). Not all matrices have an inverse.



In [1]:
#  Example :  Example of Inverse of the Matrix in Scipy.

import numpy as np
from scipy.linalg import inv

A = np.array([[1, 2], [3, 4]])
A_inv = inv(A)
print("Inverse:\n", A_inv)


Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## Features of Inverse of the Matrix in Scipy.

## Only Square Matrices Have Inverses.
    
A Matrix must be Square(same Number of Rows and Columns) to have an Inverse. If the Matrix is not Square, attempting to Compute its Inverse will Result in an Error.

In [2]:
B = np.array([[1, 2, 3], [4, 5, 6]])
# inv(B)  # This will raise an error because B is not square


## SciPy Provides inv() for Matrix Inversion.


- In SciPy, the function used for finding the Inverse of a Matrix is scipy.linalg.inv(). This Function is part of the scipy.linalg Module and is used for efficient linear algebra computations.

In [3]:
from scipy.linalg import inv

C = np.array([[2, 5], [1, 3]])
C_inv = inv(C)
print(C_inv)


[[ 3. -5.]
 [-1.  2.]]


## Singular Matrices Do Not Have an Inverse.

- A Matrix is Singular if its determinant is zero. Such matrices cannot be inverted because they are not full rank (they lose dimensional information).

In [12]:
import numpy as np
from scipy.linalg import inv, det
from scipy.linalg import LinAlgError

# Define a singular matrix (det = 0)
A = np.array([[2, 4],
              [1, 2]])  # Second row is half of the first → linearly Dependent.

# Check the determinant
print("Determinant:", det(A))  # Output: 0.0


Determinant: 0.0


## Determinant Can Predict Invertibility.

- If the Determinant is 0, the Matrix is not Invertible.

In [10]:
import numpy as np
from scipy.linalg import inv, det  

N = np.array([[1, 2], [3, 6]])
print(det(N))  # Output: 0.0 → singular matrix


0.0


## Useful for Solving Linear Systems (Ax = b).


- Although solve() is better, you can use the inverse to find x in linear systems

In [6]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = inv(A) @ b
print(x)


[2. 3.]


In [7]:
from scipy.linalg import solve
x2 = solve(A, b)
print(np.allclose(x, x2))  # True


True


In [8]:
b2 = np.array([[9], [8]])
x3 = inv(A) @ b2
print(x3)


[[2.]
 [3.]]


## SciPy Provides scipy.linalg.inv().

- SciPy's inv() Function is part of scipy.linalg, which is Optimized for Numerical Operations.

In [9]:
from scipy.linalg import inv

D = np.array([[4, 7], [2, 6]])
print(inv(D))


[[ 0.6 -0.7]
 [-0.2  0.4]]


## 10 - 20 Examples of Codes of Inverse of the Matrix in SciPy.

## Basic 2×2 Matrix Inversion.

In [13]:
import numpy as np
from scipy.linalg import inv

A = np.array([[1, 2], [3, 4]])
print(inv(A))


[[-2.   1. ]
 [ 1.5 -0.5]]


## Identity Matrix (Inverse is itself).

In [14]:
I = np.eye(3)
print(inv(I))


[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


## Diagonal Matrix Inverse.

In [15]:
D = np.diag([2, 4, 8])
print(inv(D))  # Inverse is 1/2, 1/4, 1/8 on diagonal


[[ 0.5   -0.    -0.   ]
 [ 0.     0.25  -0.   ]
 [ 0.     0.     0.125]]


## Check Product A × A⁻¹ = I.

In [16]:
A = np.array([[4, 7], [2, 6]])
A_inv = inv(A)
print(np.allclose(A @ A_inv, np.eye(2)))  # Should be True


True


## Inverse of Matrix with Random Elements.

In [17]:
np.random.seed(0)
R = np.random.rand(3, 3)
print(inv(R))


[[ 1.98960852  1.79913766 -2.4503547 ]
 [ 2.87590887 -3.14471165  0.30888212]
 [-3.56482088  2.09314855  1.86454351]]


## Solve Ax = b using Inverse.

In [18]:
A = np.array([[2, 3], [1, 2]])
b = np.array([8, 5])
x = inv(A) @ b
print(x)


[1. 2.]


## Inverse of the Matrix with Complex Numbers.

In [19]:
C = np.array([[1+2j, 3], [4, 5+1j]])
print(inv(C))


[[-0.16831683-0.31683168j  0.13366337+0.16336634j]
 [ 0.17821782+0.21782178j  0.06435644-0.14356436j]]


## Using scipy.linalg.det() to Check Invertibility.

In [20]:
from scipy.linalg import det

A = np.array([[1, 2], [2, 4]])
print(det(A))  # 0 → Singular


0.0


## Check if Inverse of Inverse is Original.

In [ ]:
A = np.array([[3, 1], [4, 2]])
A_inv = inv(A)
print(np.allclose(inv(A_inv), A))


## Inverse of the Matrix with Negative Elements.



In [21]:
N = np.array([[1, -2], [-3, 4]])
print(inv(N))


[[-2.  -1. ]
 [-1.5 -0.5]]
