## Matrix Multiplication in SciPy.


- Matrix Multiplication in SciPy is a Binary Operation that takes a Pair of Matrices and Produces another Matrix.

- It is only defined when the Number of Columns in the First Matrix equals the Number of Rows in the second.



In [1]:
# Example 1  : Basic Example of Matrix Multiplication in SciPy.

import numpy as np
from scipy import linalg

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

# Matrix multiplication using @
C = A @ B
print("A @ B =\n", C)

# Alternatively, using scipy.linalg.blas
from scipy.linalg.blas import dgemm
D = dgemm(alpha=1.0, a=A, b=B)
print("Using scipy.linalg.blas.dgemm:\n", D)


A @ B =
 [[ 4  4]
 [10  8]]
Using scipy.linalg.blas.dgemm:
 [[ 4.  4.]
 [10.  8.]]


## Dense Matrix Multiplication.

- Dense Matrices are regular NumPy Arrays(np.array) where most or all Elements are Non - Zero. 
    
- Dense Matrix Multiplication is the Standard Matrix Product, performed using either    :   The @ Operator(Python 3.5+),  np.dot() or scipy.linalg.blas for low-level control.

- SciPy uses optimized BLAS(Basic Linear Algebra Subprograms) libraries for High Performance.



In [2]:
# Example 1  :  Simple 2×2 Dense Matrix Multiplication.

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A @ B)


[[19 22]
 [43 50]]


In [3]:
# Example 2 : Using np.dot().

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))


[[19 22]
 [43 50]]


In [4]:
# Example 3  :  Using scipy.linalg.blas.dgemm.

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(dgemm(alpha=1.0, a=A, b=B))



[[19. 22.]
 [43. 50.]]


## Features of Dense Matrix Multiplication in SciPy.

## Simple and Readable Syntax.

- You can perform matrix multiplication using  : @ Operator(Pythonic), np.dot() and np.matmul().

In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A @ B)           # Using @ operator
print(np.dot(A, B))    # Using np.dot()
print(np.matmul(A, B)) # Using np.matmul()


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## Compatible with Vectors and Higher Dimensions.

- Dense Matrices can be Multiplied with 1D and Higher - Dimensional Arrays.

In [2]:
v = np.array([1, 2])
print(A @ v)  # Matrix-vector multiplication

A3D = np.random.rand(5, 2, 3)
B3D = np.random.rand(5, 3, 4)
C3D = np.matmul(A3D, B3D)
print(C3D.shape)  # (5, 2, 4)


[ 5 11]
(5, 2, 4)


## Supports Float, Integer, and Complex Data - Types.

- Dense Multiplication works with various Data -  Types(int, float, complex).

In [3]:
# Float32
Af = np.array([[1, 2], [3, 4]], dtype=np.float32)
Bf = np.array([[5, 6], [7, 8]], dtype=np.float32)
print(Af @ Bf)

# Complex numbers
Ac = np.array([[1+2j, 2], [3, 4+1j]])
print(Ac @ Ac)


[[19. 22.]
 [43. 50.]]
[[ 3.+4.j 10.+6.j]
 [15.+9.j 21.+8.j]]


## Supports Transpose Multiplication.

- Matrix Transposition is often needed for Computing Symmetric Products like  A^T.A or A.A^T.


In [4]:
X = np.random.rand(3, 2)
print(X.T @ X)  # 2x2 matrix
print(X @ X.T)  # 3x3 matrix


[[1.41240932 1.16078829]
 [1.16078829 1.68124939]]
[[0.49299054 0.84324596 0.25381682]
 [0.84324596 1.84362248 0.93549007]
 [0.25381682 0.93549007 0.75704569]]


## Power and Exponential of Matrices.


- Use scipy.linalg.matrix_power() or scipy.linalg.expm() for Advanced Linear Algebra Operations.

In [6]:
import numpy as np
from scipy.linalg import expm
from numpy.linalg import matrix_power  # Correct import

A = np.array([[2, 0], [0, 3]])
print(matrix_power(A, 3))  # A^3

B = np.array([[0, 1], [-2, -3]])
print(expm(B))  # Matrix Exponential


[[ 8  0]
 [ 0 27]]
[[ 0.6004236   0.23254416]
 [-0.46508832 -0.09720887]]


## Broadcast and Batch Multiplication.


- Matrix Multiplication supports Broadcasting and Batched Operations across Arrays.

In [7]:
X = np.random.rand(64, 128)
w = np.random.rand(128)
print(X @ w)  # 64 x 1 vector

A = np.random.rand(10, 4, 5)
B = np.random.rand(10, 5, 3)
print(np.matmul(A, B).shape)  # (10, 4, 3)


[31.23041864 30.87443546 31.00283583 27.3825077  32.03030883 29.14332232
 30.70668807 27.88103727 30.63277663 28.59527393 29.52096159 31.52095356
 31.45998378 29.4562783  32.64643867 30.51398617 30.42652434 28.35860889
 31.28696514 27.4703049  34.39450149 31.49119724 32.34243975 30.61784713
 29.74243209 30.95357079 29.11967555 31.30420577 30.79434508 31.49563985
 31.58674326 31.48149607 30.48555157 28.70628479 30.83720895 32.823761
 27.86910865 30.75594462 29.01744393 29.49912487 29.55744223 31.34690796
 28.32459153 32.07119526 29.63027919 28.75422007 30.27479112 34.43494669
 31.67991728 31.44534831 31.39828276 32.53753189 30.43056956 32.73464621
 30.88974032 29.78701289 29.89692047 29.32611384 31.26071007 33.01310539
 27.90623981 29.51757107 30.94720509 33.59030969]
(10, 4, 3)


## Chain Multiplication and Associativity.

- Multiple Matrices can be Multiplied in sequence using Chained @ Operators.

In [8]:
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
C = np.random.rand(2, 2)

result = A @ B @ C
print(result)


[[0.86852554 1.46721527]
 [0.93299605 1.56196599]]


## Compatibility with Linear Algebra Solvers.


- Dense Matrix Multiplication works with other SciPy Functions like LU Decomposition and System Solvers.

In [9]:
from scipy.linalg import solve

A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = solve(A, b)
print(x)  # Solves Ax = b


[2. 3.]


## Examples of Dense Matrix Multiplication in SciPy.


In [17]:
import numpy as np
from scipy import linalg
from scipy.linalg.blas import dgemm

# 1. Basic 2x2 Matrix Multiplication.

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A @ B)  # Using @ operator

[[19 22]
 [43 50]]


In [18]:
import numpy as np
from scipy import linalg
from scipy.linalg.blas import dgemm

# 2. Using np.dot.

print(np.dot(A, B))

[[19 22]
 [43 50]]


In [19]:
import numpy as np
from scipy import linalg
from scipy.linalg.blas import dgemm

# 3. Using np.matmul.

print(np.matmul(A, B))

[[19 22]
 [43 50]]


In [20]:
import numpy as np
from scipy import linalg
from scipy.linalg.blas import dgemm

# 4. Multiply with Identity Matrix.

I = np.eye(2)
print(A @ I)  # Should be same as A.

[[1. 2.]
 [3. 4.]]


In [21]:
import numpy as np
from scipy import linalg
from scipy.linalg.blas import dgemm

# 5. Transpose Matrix Multiplication.

print(A.T @ A)  # Creates Symmetric Matrix.


[[10 14]
 [14 20]]


In [22]:
import numpy as np
from scipy import linalg
from scipy.linalg.blas import dgemm

# 6. Multiply with Vector.

v = np.array([1, 2])
print(A @ v)  # 2x2 @ 2x1 -> 2x1


[ 5 11]


In [23]:
import numpy as np
from scipy import linalg
from scipy.linalg.blas import dgemm


# 7. Matrix Squared.

print(A @ A)  # A^2


[[ 7 10]
 [15 22]]


In [25]:
import numpy as np
from numpy.linalg import matrix_power  # Use NumPy, not SciPy.

A = np.array([[2, 0], [0, 3]])
print(matrix_power(A, 3))  # A^3 = A * A * A.


[[ 8  0]
 [ 0 27]]


In [27]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy.

# 9. Multiply with a Zero Matrix.

Z = np.zeros((2, 2))
print(A @ Z)  # All Zeros

[[0. 0.]
 [0. 0.]]


In [28]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy

# 10. Double - Precision GEMM.


print(dgemm(alpha=1.0, a=A, b=B))


[[10. 12.]
 [21. 24.]]


In [29]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy


# 11. Chain multiplication
C = np.array([[1, 0], [0, 1]])
print(A @ B @ C)

[[10 12]
 [21 24]]


In [30]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy

# 12. Multiply large random matrices.

A_large = np.random.rand(100, 100)
B_large = np.random.rand(100, 100)
C_large = A_large @ B_large
print(C_large.shape)




(100, 100)


In [31]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy


# 13. Complex matrix multiplication
A_c = np.array([[1+2j, 2+3j], [3+4j, 4+5j]])
print(A_c @ A_c)



[[ -9.+21.j -11.+29.j]
 [-13.+41.j -15.+57.j]]


In [32]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy

# 14. Matrix-vector broadcast
X = np.random.rand(64, 128)
w = np.random.rand(128)
print(X @ w)


[32.44919468 30.05789076 26.42331369 35.23410112 31.91908832 34.55876191
 33.33199279 31.36715759 30.23778467 32.89855386 29.09543486 32.33589439
 31.91329187 31.90879126 29.66456899 30.21342495 34.68938723 33.71015697
 33.36905232 28.45689203 31.48990569 33.06296537 31.81808289 35.09663912
 29.86468399 31.92257415 28.13309749 30.7630297  30.26135737 27.08067132
 31.72449639 31.5612496  30.65906877 33.33775751 27.29576544 30.04389024
 34.05432798 36.09078297 33.68405889 32.12409604 30.60049852 32.34964857
 28.32385836 31.3742762  29.36989086 34.1010678  30.12414781 29.6503864
 34.42100745 30.47388646 33.06968165 32.57648191 28.76530614 34.34210867
 32.9736945  30.99654571 30.62854095 31.77019072 30.18811002 35.2489612
 32.58200097 33.20285272 34.36572167 29.89391661]


In [33]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy

# 15. Batch multiplication
A_batch = np.random.rand(10, 2, 3)
B_batch = np.random.rand(10, 3, 4)
C_batch = np.matmul(A_batch, B_batch)
print(C_batch.shape)  # (10, 2, 4)



(10, 2, 4)


In [34]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy


# 16. Diagonal matrix multiplication
D = np.diag([1, 2, 3])
E = np.random.rand(3, 3)
print(D @ E)



[[0.02658531 0.26214055 0.43965343]
 [1.84116461 1.42105904 0.06140384]
 [1.83582647 0.74747698 0.27115945]]


In [35]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy


# 17. Symmetric Multiplication(covariance-like).

X = np.random.rand(5, 3)
print(X.T @ X)



[[1.40201891 0.86365186 0.74693719]
 [0.86365186 1.52076168 0.90796563]
 [0.74693719 0.90796563 0.89955201]]


In [37]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy


# 18. Matrix Exponential.

M = np.array([[0, 1], [-2, -3]])
print(linalg.expm(M))

[[ 0.6004236   0.23254416]
 [-0.46508832 -0.09720887]]


In [38]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy


# 19. Multiplication with float32.

A_f32 = A.astype(np.float32)
B_f32 = B.astype(np.float32)
print(A_f32 @ B_f32)



[[10. 12.]
 [21. 24.]]


In [40]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy

# 20. Multiply Row Vector with Matrix.

r = np.array([[1, 2]])
print(r @ A)

[[2 6]]


In [41]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy


# 21. Multiply Matrix with Column Vector.

c = np.array([[1], [2]])
print(A @ c)


[[2]
 [6]]


In [42]:
import numpy as np
from numpy.linalg import matrix_power  # Use Numpy, not SciPy


# 22. Multiply Matrices of different Shapes(valid inner dim).

A2 = np.random.rand(3, 5)
B2 = np.random.rand(5, 2)
print(A2 @ B2)  # (3x5) * (5x2) = (3x2)

[[1.74211607 1.7235407 ]
 [1.9259266  1.566477  ]
 [1.89503962 1.56020184]]


## Sparse Matrix Multiplication.

- A Sparse Matrix is a Matrix where most values are Zero. Instead of Storing all Values, SciPy stores only the Non - Zero Values to save Memory and Speed up Calculations.

In [44]:
# Example : Basic Example of Sparse Matrix Multiplication.

from scipy.sparse import csr_matrix

dense = [[0, 0, 5],
         [0, 0, 0],
         [1, 0, 0]]

sparse = csr_matrix(dense)
print(sparse)


<Compressed Sparse Row sparse matrix of dtype 'int32'
	with 2 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	5
  (2, 0)	1


## Features of Sparse Matrix Multiplication.

## Storing Large Matrices with mostly Zeros wastes Memory. Sparse Matrices are much more Efficient when only a few values are Non - Zero.


In [45]:
import numpy as np
from scipy.sparse import random

dense = np.zeros((1000, 1000))
sparse = random(1000, 1000, density=0.01, format='csr')

print("Dense size:", dense.nbytes)
print("Sparse size (approx):", sparse.data.nbytes)


Dense size: 8000000
Sparse size (approx): 80000


## SciPy allows Multiplication using @(Matrix Multiply) or .dot() Methods — just like NumPy.

In [46]:
from scipy.sparse import csr_matrix

A = csr_matrix([[0, 2], [3, 0]])
B = csr_matrix([[1, 0], [0, 4]])

C = A @ B
print(C.toarray())


[[0 8]
 [3 0]]


## You Can Multiply Sparse × Dense.


- A Sparse Matrix can also be Multiplied with a Regular NumPy Matrix. The result is a Dense Matrix.

In [47]:
import numpy as np

dense = np.array([[1, 2], [3, 4]])
print((A @ dense))


[[6 8]
 [3 6]]


## Efficient for Large Matrix Operations.

- Sparse Matrix Multiplication is very Fast and Efficient for large-scale data, like graphs or Machine Learning Models.

In [48]:
from scipy.sparse import random

big_sparse = random(1000, 1000, density=0.005, format='csr')
v = np.ones(1000)

# Multiply with a vector
result = big_sparse @ v
print(result.shape)


(1000,)


## Transpose Multiplication is Easy.

- You can Multiply a Sparse Matrix with its Transpose using .T.

In [49]:
A = csr_matrix([[0, 1], [2, 0]])
result = A.T @ A
print(result.toarray())


[[4 0]
 [0 1]]


## Matrix × Vector Multiplication.

- You can Multiply a Sparse Matrix with a NumPy Vector for Operations like Ax = b.

In [50]:
x = np.array([1, 2])
print(A @ x)


[2 2]


## Can Convert to Dense if Needed.

- If you need to Apply Operations Unsupported by Sparse Format(like Exponentials), convert it to Dense.

In [51]:
A_dense = A.toarray()
print(A_dense)


[[0 1]
 [2 0]]


## Examples of Sparse Matrix Multiplication.

In [52]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 1. Create sparse matrix from dense
dense = np.array([[0, 0], [5, 0]])
sparse = csr_matrix(dense)
print(sparse)

<Compressed Sparse Row sparse matrix of dtype 'int32'
	with 1 stored elements and shape (2, 2)>
  Coords	Values
  (1, 0)	5


In [53]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 2. Sparse matrix-vector multiplication
v = np.array([1, 2])
print(sparse @ v)


[0 5]


In [54]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 3. Sparse Matrix - Matrix Multiplication.

A = csr_matrix([[0, 1], [2, 0]])
B = csr_matrix([[3, 0], [0, 4]])
print((A @ B).toarray())

[[0 4]
 [6 0]]


In [55]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 4. Multiply with Identity Matrix.

I = csr_matrix(np.eye(2))
print((A @ I).toarray())  # Same as A


[[0. 1.]
 [2. 0.]]


In [57]:
import numpy as np
from scipy.sparse import csr_matrix

A = csr_matrix([[0, 2], [3, 0]])  # sparse matrix
D = np.array([[1, 0], [0, 1]])    # dense identity matrix

result = A @ D  # multiplication gives a dense matrix
print(result)


[[0 2]
 [3 0]]


In [58]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 6. COO format Multiplication.

coo = coo_matrix([[0, 2], [3, 0]])
print((coo @ coo).toarray())

[[6 0]
 [0 6]]


In [59]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 7. CSC format Multiplication.

csc = csc_matrix([[1, 0], [0, 2]])
print((csc @ csc).toarray())



[[1 0]
 [0 4]]


In [61]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 8. Sparse * Dense Vector.

x = np.array([10, 20])
print(A @ x)

[40 30]


In [62]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 9. Random Sparse Matrix Multiplication.

S1 = sparse_random(100, 100, density=0.01, format='csr')
S2 = sparse_random(100, 100, density=0.01, format='csr')
print((S1 @ S2).shape)

(100, 100)


In [63]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 10. Sparse Multiplication Result is still Sparse.


result = S1 @ S2
print(type(result))  # csr_matrix


<class 'scipy.sparse._csr.csr_matrix'>


In [64]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 11. Sparse dot with Transpose.

print((A.T @ A).toarray())



[[9 0]
 [0 4]]


In [65]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 12. Sparse + Sparse then Multiply.

sum_sparse = A + B
print((sum_sparse @ A).toarray())

[[ 6  6]
 [12  6]]


In [68]:
import numpy as np
from scipy.sparse import csr_matrix

# Define Sparse Matrices.

A = csr_matrix([[0, 2], [3, 0]])
B = csr_matrix([[1, 0], [0, 4]])

# 13. Sparse scaling then multiply
A_scaled = A * 2  # scale each element of A by 2
result = A_scaled @ B  # multiply scaled A with B
print(result.toarray())


[[ 0 16]
 [ 6  0]]


In [69]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 14. Use Shape Properties.

print(A.shape, B.shape)

(2, 2) (2, 2)


In [70]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 15. Create Sparse Diagonal.

diag_sparse = csr_matrix(np.diag([1, 2, 3]))
print((diag_sparse @ diag_sparse).toarray())



[[1 0 0]
 [0 4 0]
 [0 0 9]]


In [71]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 16. Matrix Exponential(Convert to Dense First).

dense_A = A.toarray()
from scipy.linalg import expm
print(expm(dense_A))


[[5.83438641 4.69326218]
 [7.03989326 5.83438641]]


In [72]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 17. Multiply Sparse with Column Vector.

col = np.array([[1], [2]])
print(A @ col)


[[4]
 [3]]


In [73]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 18. Multiply Row Vector with Sparse.

row = np.array([[1, 2]])
print(row @ A)


[[6 2]]


In [74]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 19. Sparse Power(Convert to Dense First).

print(np.linalg.matrix_power(A.toarray(), 3))


[[ 0 12]
 [18  0]]


In [75]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 20. Multiply Sparse with Random Dense Matrix.


dense_rand = np.random.rand(2, 2)
print((A @ dense_rand).shape)


(2, 2)


In [76]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random# 

# 21. Dense matrix from Sparse Result.

result = A @ B
print(result.toarray())

[[0 8]
 [3 0]]


In [77]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, random as sparse_random

# 22. Dot Product with Sparse.

print(A.dot(B).toarray())

[[0 8]
 [3 0]]
