## Linear Algebra operations in SciPy.


- In SciPy, a key subpackage for Linear Algebra is scipy.linalg, which extends the capabilities of numpy.linalg by offering more advanced routines. It allows users to Perform Matrix Operations, Solve Systems of Equations, Compute Matrix Factorizations, and more.



## Matrix Multiplication.

- Matrix Multiplication is a core operation in Linear Algebra where the Product of Two Matrices A and B is defined only if the number of columns in 
A equals the number of rows in B.


In [2]:
import numpy as np
from scipy import linalg

A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

C = A @ B  # or np.dot(A, B)
print("Matrix Product:\n", C)


Matrix Product:
 [[ 4  4]
 [10  8]]


## Solving Linear Systems (Ax = b). 

- Solves the equation Ax = b, A is a matrix and b is a vector or matrix.

In [3]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = linalg.solve(A, b)
print("Solution x:", x)


Solution x: [2. 3.]


## Matrix Inversion.


- Finds the Inverse A^ - 1 of a square matrix A, such that A. A^-1 = I(Identity Matrix).
  


In [4]:
A = np.array([[1, 2], [3, 4]])
inv_A = linalg.inv(A)
print("Inverse of A:\n", inv_A)


Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## Determinant of a Matrix.

- The determinant is a scalar that summarizes certain properties of the matrix (e.g., invertibility).

In [5]:
A = np.array([[1, 2], [3, 4]])
det_A = linalg.det(A)
print("Determinant of A:", det_A)


Determinant of A: -2.0


## Eigenvalues and Eigenvectors.

- Solves Av=λv, where λ is an Eigenvalue and v is its Eigenvector.

In [6]:
A = np.array([[4, -2], [1, 1]])
eigvals, eigvecs = linalg.eig(A)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)


Eigenvalues: [3.+0.j 2.+0.j]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


## LU Decomposition.


- Decomposes a matrix A into L (lower), U (upper), and permutation matrix P, so  PA=LU.

In [7]:
A = np.array([[3, 1], [1, 2]])
P, L, U = linalg.lu(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)


P:
 [[1. 0.]
 [0. 1.]]
L:
 [[1.         0.        ]
 [0.33333333 1.        ]]
U:
 [[3.         1.        ]
 [0.         1.66666667]]


## QR Decomposition.


- Factorizes a matrix A into an orthogonal matrix, Q and upper triangular matrix R such that A = QR.

In [8]:
A = np.array([[1, 1], [1, -1], [1, 2]])
Q, R = linalg.qr(A)
print("Q:\n", Q)
print("R:\n", R)


Q:
 [[-0.57735027  0.15430335 -0.80178373]
 [-0.57735027 -0.77151675  0.26726124]
 [-0.57735027  0.6172134   0.53452248]]
R:
 [[-1.73205081 -1.15470054]
 [ 0.          2.1602469 ]
 [ 0.          0.        ]]


## Singular Value Decomposition(SVD).

- Decomposes A into UΣV^T. Useful in dimensionality reduction, pseudoinverse, etc.

In [9]:
A = np.array([[1, 0], [0, -2], [3, 0]])
U, s, Vh = linalg.svd(A)
print("U:\n", U)
print("Singular values:", s)
print("Vh:\n", Vh)


U:
 [[-0.31622777  0.         -0.9486833 ]
 [ 0.          1.          0.        ]
 [-0.9486833   0.          0.31622777]]
Singular values: [3.16227766 2.        ]
Vh:
 [[-1. -0.]
 [-0. -1.]]


## Norms of Vectors and Matrices.

- Norms measure the size or length of a vector/matrix. Common norms: L2 (Euclidean), Frobenius.

In [10]:
v = np.array([3, 4])
matrix = np.array([[1, 2], [3, 4]])

print("L2 norm of vector:", linalg.norm(v))
print("Frobenius norm of matrix:", linalg.norm(matrix, 'fro'))


L2 norm of vector: 5.0
Frobenius norm of matrix: 5.477225575051661


## Pseudo-Inverse (Moore-Penrose).


- Used when a matrix is not square or not invertible. Computes a "best fit" inverse.

In [11]:
A = np.array([[1, 2], [3, 4], [5, 6]])
pinv_A = linalg.pinv(A)
print("Pseudo-inverse:\n", pinv_A)


Pseudo-inverse:
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


## Cholesky Decomposition.


- Decomposes a symmetric, positive-definite matrix A into LL^T,  used in efficient numerical solving.

In [12]:
A = np.array([[4, 2], [2, 3]])
L = linalg.cholesky(A, lower=True)
print("Cholesky decomposition (L):\n", L)


Cholesky decomposition (L):
 [[2.         0.        ]
 [1.         1.41421356]]


## Checking Matrix Properties(e.g., Rank, Condition Number).


- Rank: Number of linearly independent rows/columns.

- Condition number: Indicates numerical stability.

In [13]:
A = np.array([[1, 2], [3, 4]])
print("Rank of A:", np.linalg.matrix_rank(A))
print("Condition number of A:", linalg.cond(A))


Rank of A: 2


AttributeError: module 'scipy.linalg' has no attribute 'cond'

## Solving Systems of Equations.

- Real-world problems in engineering, physics, and economics are often reduced to systems of linear equations. Efficient solutions are critical.



In [14]:
from scipy.linalg import solve
import numpy as np

A = np.array([[3, 2], [1, 2]])
b = np.array([5, 5])
x = solve(A, b)
print("Solution x:", x)


Solution x: [0.  2.5]


## Foundation for Machine Learning & AI.

- ML algorithms like linear regression, PCA, and neural networks are built on matrix operations like dot products, inverses, and decompositions.

In [15]:
X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([1, 2, 3])
theta = np.linalg.pinv(X.T @ X) @ X.T @ y
print("Theta (parameters):", theta)


Theta (parameters): [-5.55111512e-16  1.00000000e+00]


## Performance and Optimization.

- SciPy uses low-level optimized libraries (like LAPACK/BLAS), making it far faster than manual loops for matrix ops.

In [16]:
from scipy.linalg import inv
A = np.random.rand(100, 100)
A_inv = inv(A)


## Numerical Stability in Computations.


- Functions like solve() are preferred over directly inverting matrices due to better accuracy and stability in floating-point arithmetic.

In [17]:
from scipy.linalg import solve
A = np.array([[1e-10, 1], [1, 1]])
b = np.array([1, 2])
x = solve(A, b)
print("Numerically stable solution:", x)


Numerically stable solution: [1. 1.]


## Simulation and Modeling.


- Modeling physical systems (e.g., electrical circuits, fluid dynamics) involves linear algebra to handle interrelated variables.

In [18]:
# Ohm's Law: V = IR → I = V / R using matrix form
R = np.array([[2, -1], [-1, 2]])
V = np.array([1, 0])
I = solve(R, V)
print("Current vector I:", I)


Current vector I: [0.66666667 0.33333333]


## Dimensionality Reduction(SVD, PCA).

- Used in data compression and visualization. SciPy’s svd() decomposes data for removing redundancy.

In [19]:
from scipy.linalg import svd
A = np.array([[1, 2], [3, 4], [5, 6]])
U, s, Vh = svd(A)
print("Singular values:", s)


Singular values: [9.52551809 0.51430058]


## Error Minimization and Regression.

- Linear algebra helps find least-squares solutions—core to regression and optimization techniques.

In [20]:
from scipy.linalg import lstsq
A = np.array([[1, 1], [1, 2], [1, 3]])
b = np.array([1, 2, 2])
x, res, rnk, s = lstsq(A, b)
print("Least Squares Solution:", x)


Least Squares Solution: [0.66666667 0.5       ]


## Matrix Decomposition for Efficient Computation.


- Decompositions (LU, QR, Cholesky) simplify solving systems, inverting, and finding eigenvalues more efficiently.

In [21]:
from scipy.linalg import lu
A = np.array([[3, 1], [1, 2]])
P, L, U = lu(A)
print("L:\n", L)
print("U:\n", U)


L:
 [[1.         0.        ]
 [0.33333333 1.        ]]
U:
 [[3.         1.        ]
 [0.         1.66666667]]
