## Stacking and Splitting in Arrays.


- Stacking means Joining Two or More Arrays along a New or Existing Axis. Common Stacking Functions: np.stack, np.hstack, np.vstack, np.dstack.

- Stacking joins two or more arrays into a single larger array.

- You can stack along rows, columns, or depth using vstack, hstack, dstack.

- np.stack() creates a new axis to combine arrays, unlike hstack or vstack..

- When stacking with np.stack(), arrays must have identical shapes.

- Stack multiple arrays(e.g., images, samples) to build a batch of data.

- Use column_stack() to stack 1D arrays into a 2D matrix (columns)..

- vstack() adds arrays as new rows in 2D.

- hstack() joins arrays side-by-side, increasing columns.

- dstack() joins 2D arrays into a 3D volume (stacking in depth.

- np.row_stack() is functionally identical to np.vstack().

- Carefully choosing the axis affects how the output is structured.


In [1]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

stacked = np.stack((a, b))
print(stacked)  # Adds a new axis


[[1 2]
 [3 4]]


In [2]:
# Combines Arrays Together.

import numpy as np
a = np.array([1, 2])
b = np.array([3, 4])
print(np.stack((a, b)))  # Stacked vertically


[[1 2]
 [3 4]]


In [3]:
# Supports Different Stack Directions.

print(np.vstack((a, b)))   # Vertical stack
print(np.hstack((a, b)))   # Horizontal stack


[[1 2]
 [3 4]]
[1 2 3 4]


In [4]:
# Creates New Dimensions(Axes).

c = np.stack((a, b), axis=1)
print(c)


[[1 3]
 [2 4]]


In [5]:
# All Arrays Must Be Same Shape.

a = np.ones((2,))
b = np.zeros((2,))
print(np.stack((a, b)))  


[[1. 1.]
 [0. 0.]]


In [6]:
# Useful in Image or Data Batching.

img1 = np.array([[1, 2], [3, 4]])
img2 = np.array([[5, 6], [7, 8]])
batch = np.stack((img1, img2))
print(batch.shape)  # (2, 2, 2)


(2, 2, 2)


In [12]:
# Stacking 1D Arrays as Columns.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.column_stack((a, b)))


[[1 4]
 [2 5]
 [3 6]]


In [9]:
# Vertical Stack Adds Rows.

x = np.array([10, 20])
y = np.array([30, 40])
print(np.vstack((x, y)))


[[10 20]
 [30 40]]


In [10]:
# Horizontal Stack Adds Columns.

x = np.array([[1], [2]])
y = np.array([[3], [4]])
print(np.hstack((x, y)))


[[1 3]
 [2 4]]


In [11]:
# Depth Stack Adds a Third Dimension.

x = np.array([[1, 2]])
y = np.array([[3, 4]])
print(np.dstack((x, y)))


[[[1 3]
  [2 4]]]


## Vertical Stacking i.e. np.vstack.


- np.vstack() is a NumPy function that stacks arrays vertically — i.e., row-wise — by joining them along axis 0 (the first axis). It increases the number of rows in the resulting array while keeping the columns consistent.

- It stacks input arrays vertically by adding more rows.

- If you pass 1D arrays, vstack() converts them into rows.

- It’s often used to combine data points (e.g., training samples) vertically.

- Column counts must match, otherwise it throws an error.

- Not just 1D arrays, works with already 2D matrices.

- Pass a tuple or list of multiple arrays.

- Each array becomes a row in the final array.

- Especially when output shape must be(n, features).

- If you mix 1D and 2D arrays, it converts 1D to row.


 


In [14]:
# Stacks Arrays on Top of Each Other(Row-wise).

import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack((a, b)))


[[1 2]
 [3 4]]


In [13]:
# Converts 1D Arrays into 2D Automatically.

x = np.array([10, 20])
y = np.array([30, 40])
print(np.vstack((x, y)))


[[10 20]
 [30 40]]


In [15]:
# Useful for Data Batching in ML/DL.

data1 = np.array([1, 2])
data2 = np.array([3, 4])
batch = np.vstack((data1, data2))
print(batch)


[[1 2]
 [3 4]]


In [17]:
# All Arrays Must Have Same Number of Columns.

# x = np.array([1, 2])
# y = np.array([3, 4, 5])
# np.vstack((x, y))  # ValueError


In [18]:
# Works with 2D Arrays Too.

a = np.array([[1, 2]])
b = np.array([[3, 4]])
print(np.vstack((a, b)))


[[1 2]
 [3 4]]


In [19]:
# Can Stack More than Two Arrays at Once.

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
print(np.vstack((a, b, c)))


[[1 2]
 [3 4]
 [5 6]]


In [20]:
# Creates Higher Number of Rows in Output.

a = np.array([9, 8])
b = np.array([7, 6])
result = np.vstack((a, b))
print(result.shape)


(2, 2)


In [21]:
# Useful for Combining Feature Vectors or Predictions.

pred1 = np.array([0.1, 0.9])
pred2 = np.array([0.8, 0.2])
combined = np.vstack((pred1, pred2))
print(combined)


[[0.1 0.9]
 [0.8 0.2]]


## Vertical Stacking i.e. np.vstack.


- np.vstack() is a NumPy function that stacks arrays vertically — i.e., row-wise — by joining them along axis 0 (the first axis). It increases the number of rows in the resulting array while keeping the columns consistent.

- It stacks input arrays vertically by adding more rows.

- If you pass 1D arrays, vstack() converts them into rows.

- It’s often used to combine data points (e.g., training samples) vertically.

- Column counts must match, otherwise it throws an error.

- Not just 1D arrays, works with already 2D matrices.

- Pass a tuple or list of multiple arrays.

- Each array becomes a row in the final array.

- Especially when output shape must be(n, features).

- If you mix 1D and 2D arrays, it converts 1D to row.

- Used in simulations, data frames, etc.
  



In [29]:
# Stacks Arrays on Top of Each Other(Row-wise).

import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack((a, b)))


[[1 2]
 [3 4]]


In [30]:
# Converts 1D Arrays into 2D Automatically.

x = np.array([10, 20])
y = np.array([30, 40])
print(np.vstack((x, y)))


[[10 20]
 [30 40]]


In [31]:
# Useful for Data Batching in ML/DL.

data1 = np.array([1, 2])
data2 = np.array([3, 4])
batch = np.vstack((data1, data2))
print(batch)


[[1 2]
 [3 4]]


In [32]:
# All Arrays Must Have Same Number of Columns.

# x = np.array([1, 2])
# y = np.array([3, 4, 5])
# np.vstack((x, y))  # ValueError


In [33]:
# Works with 2D Arrays Too.

a = np.array([[1, 2]])
b = np.array([[3, 4]])
print(np.vstack((a, b)))


[[1 2]
 [3 4]]


In [34]:
# Can Stack More than Two Arrays at Once.

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
print(np.vstack((a, b, c)))


[[1 2]
 [3 4]
 [5 6]]


In [35]:
# Creates Higher Number of Rows in Output.

a = np.array([9, 8])
b = np.array([7, 6])
result = np.vstack((a, b))
print(result.shape)


(2, 2)


In [36]:
# Useful for Combining Feature Vectors or Predictions.

pred1 = np.array([0.1, 0.9])
pred2 = np.array([0.8, 0.2])
combined = np.vstack((pred1, pred2))
print(combined)


[[0.1 0.9]
 [0.8 0.2]]


In [37]:
# Works with Mixed Dimensions(Broadcasting from 1D to 2D).

a = np.array([1, 2])
b = np.array([[3, 4]])
print(np.vstack((a, b)))


[[1 2]
 [3 4]]


In [38]:
# Used in Real-Life for Logging, Storing Rows of Data.

log1 = np.array([101, 1.23])
log2 = np.array([102, 2.34])
logs = np.vstack((log1, log2))
print(logs)


[[101.     1.23]
 [102.     2.34]]


## Depth Stacking i.e. np.dstack.


- np.dstack() stacks arrays along a third axis (depth-wise). For 1D arrays, it returns a 3D array of shape (1, n, 2); for 2D, it returns (rows, cols, arrays).

- Stacks along depth(axis=2).

- Result is always 3D.

- Each input must have same shape.

- Mixes arrays into layered form

- Preserves row and column counts.

- Result shape increases in depth.

- Access slices by depth.

In [39]:
# Stacks along depth(axis=2).

a = np.array([[1, 2]])
b = np.array([[3, 4]])
print(np.dstack((a, b)))


[[[1 3]
  [2 4]]]


In [40]:
# Result is always 3D.

a = np.array([1, 2])
b = np.array([3, 4])
print(np.dstack((a, b)))  # Shape: (1, 2, 2)


[[[1 3]
  [2 4]]]


In [41]:
# Each input must have same shape.

a = np.ones((2, 2))
b = np.zeros((2, 2))
print(np.dstack((a, b)))


[[[1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]]]


In [42]:
# Mixes arrays into layered form.

a = np.array([[10, 20]])
b = np.array([[30, 40]])
print(np.dstack((a, b)))


[[[10 30]
  [20 40]]]


In [43]:
# Preserves row and column counts.

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dstack((a, b)))


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [44]:
# Result shape increases in depth.

res = np.dstack((a, b))
print(res.shape)  # (2, 2, 2)



(2, 2, 2)


In [45]:
# Access slices by depth.

stack = np.dstack((a, b))
print(stack[:, :, 0])  # First array


[[1 2]
 [3 4]]


## General Stacking i.e. np.stack.


- np.stack() joins a sequence of arrays along a new axis. Unlike hstack, vstack, etc., stack allows you to choose any axis for stacking.

- Stacks along new axis.

- In General Stacking, New dimension is added.

- Arrays must be same shape.

- Control stacking axis.

- Works on higher dimensions.

- Used in batch stacking.

- Can stack scalar values too.

- More flexible than vstack, hstack.

In [48]:
# Stacks along new axis.

a = np.array([1, 2])
b = np.array([3, 4])
print(np.stack((a, b)))  # Axis 0 by default


[[1 2]
 [3 4]]


In [49]:
# New dimension is added.

print(np.stack((a, b), axis=1))  # Shape becomes (2, 2)


[[1 3]
 [2 4]]


In [50]:
# Arrays must be same shape.

# np.stack(([1, 2], [3]))  # ValueError


In [51]:
# Control stacking axis.

print(np.stack((a, b), axis=0))
print(np.stack((a, b), axis=1))


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [52]:
# Works on higher dimensions.

x = np.ones((2, 2))
y = np.zeros((2, 2))
print(np.stack((x, y), axis=0).shape)  # (2, 2, 2)


(2, 2, 2)


In [53]:
# Used in Batch Stacking.

images = [np.random.rand(2, 2) for _ in range(3)]
print(np.stack(images).shape)  # (3, 2, 2)


(3, 2, 2)


In [54]:
# Returns 3D from 2D inputs.

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.stack((a, b), axis=2))


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [55]:
# Can stack scalar values too.

a = np.array(1)
b = np.array(2)
print(np.stack((a, b)))


[1 2]


In [56]:
# More flexible than vstack, hstack.

a = np.array([1, 2])
b = np.array([3, 4])
print(np.stack((a, b), axis=-1))  # Like column stacking


[[1 3]
 [2 4]]


## Column Stacking i.e. np.column_stack.

- np.column_stack() stacks 1D arrays as columns into a 2D array. Similar to np.hstack() but it first reshapes 1D arrays into columns.

- Stacks 1D arrays as columns.

- Result is always 2D.

- Useful for matrix construction.

- Reshapes 1D to (n, 1).

- Equivalent to hstack with reshape.

- Cannot stack 2D arrays with differing rows.

- Returns shape(n, m).

- Used in DataFrame-style preparation.

In [57]:
# Stacks 1D arrays as Columns.


a = np.array([1, 2])
b = np.array([3, 4])
print(np.column_stack((a, b)))


[[1 3]
 [2 4]]


In [58]:
# Result is always 2D.

print(np.column_stack(([5, 6], [7, 8])).shape)


(2, 2)


In [59]:
# Useful for matrix construction.

ids = np.array([101, 102])
scores = np.array([95, 88])
print(np.column_stack((ids, scores)))


[[101  95]
 [102  88]]


In [60]:
# Reshapes 1D to(n, 1).

a = np.array([9, 8])
print(np.column_stack((a,)))


[[9]
 [8]]


In [61]:
# Equivalent to hstack with reshape.

np.hstack((a[:, np.newaxis], b[:, np.newaxis]))


array([[9, 3],
       [8, 4]])

In [62]:
# Cannot stack 2D arrays with differing rows.

# np.column_stack(([1, 2], [[3], [4], [5]]))  # Error


In [63]:
# Returns shape(n, m).

x = np.array([1, 2])
y = np.array([3, 4])
print(np.column_stack((x, y)).shape)  # (2, 2)


(2, 2)


In [64]:
# Used in DataFrame-style preparation.

import pandas as pd
df = pd.DataFrame(np.column_stack(([1, 2], [3, 4])), columns=['A', 'B'])
print(df)


   A  B
0  1  3
1  2  4
