## Linear Algebra i.e. scipy.linalg in SciPy. 


- Linear Algebra is a branch of mathematics dealing with vectors, matrices, and systems of linear equations. The scipy.linalg module in SciPy provides efficient routines for linear algebra tasks, extending NumPy capabilities.



In [2]:
# Example : Solve a Linear System Ax=b. 

import numpy as np
from scipy import linalg          
A = np.array([[3, 1],
              [1, 2]])
b = np.array([9, 8])
x = linalg.solve(A, b)            
print("x =", x)


x = [2. 3.]


## Features of Linear Algebra i.e. scipy.linalg in SciPy.

## Matrix Inversion in Linear Algebra in SciPy.

- For a Square Matrix A, its Inverse A⁻¹ is a Matrix such that  :  A . A^-1  =  A^-1 . A = I, Where I is the Identity Matrix of the Same Size.

- A Matrix A has an Inverse only iff and only iff: It is Square(Same Number of Rows and Columns) and It is Non - Singular (i.e., its Determinant ≠ 0).

- It's used to  :  Solve Linear Equations  :  A . x  = b ⇒ x = A^-1 . b and Inverse Covariance Matrices in Statistics/Machine Learning.




In [13]:
# Example  :  Basic  2×2  Inverse.

import numpy as np
from scipy.linalg import inv
A = np.array([[4, 7],
              [2, 6]])
A_inv = inv(A)
print(A_inv)


[[ 0.6 -0.7]
 [-0.2  0.4]]


## Features of Matrix Inversion.


## Uniqueness.

- If a matrix A is Invertible, its inverse A⁻¹ is Unique. No Matrix has more than one Inverse.

In [4]:
from scipy.linalg import inv
import numpy as np

A = np.array([[2, 3], [1, 4]])
A_inv = inv(A)
print("A⁻¹:\n", A_inv)


A⁻¹:
 [[ 0.8 -0.6]
 [-0.2  0.4]]


##  Only Square Matrices Can Be Inverted.

- Only matrices of size n×n(Same Number of Rows and Columns) can be inverted  and  Non - Square Matrices do not have Inverses.

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix
# inv(A)  # Raises ValueError: expected square matrix


## Determinant ≠ 0 Is a must.


- A matrix must be non-singular (i.e., det(A) ≠ 0) to have an inverse. A zero determinant means the matrix is not invertible.



In [7]:
from scipy.linalg import det

B = np.array([[2, 4], [1, 2]])
print("det(B):", det(B))  # Output: 0.0 → Singular


det(B): 0.0


## Inverse Acts Like Division in Matrix Algebra.

- To Solve Linear Equations  A.x = b, use :  x = A^-1.b. 

In [8]:
b = np.array([8, 3])
x = A_inv @ b
print("Solution x:", x)


Solution x: [ 4.6 -0.4]


## Inverse of the Inverse Returns the Original Matrix.


- (A^-1)^-1  =  A


In [9]:
A_double_inv = inv(A_inv)
print("A after double inversion:\n", A_double_inv)  # Same as original A


A after double inversion:
 [[2. 3.]
 [1. 4.]]


## Inverse of Identity Matrix is itself.

- I ^ - 1 = I.

In [10]:
I = np.eye(3)
I_inv = inv(I)
print("Inverse of Identity:\n", I_inv)


Inverse of Identity:
 [[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


## Inverse of a Product.

- (A . B) ^ -1 = A ^ -1 . B ^ - 1   — Order matters in this.

In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [0, 2]])
AB_inv = inv(A @ B)
B_inv_A_inv = inv(B) @ inv(A)
print("AB inverse:\n", AB_inv)
print("B⁻¹ A⁻¹:\n", B_inv_A_inv)  # Should match


AB inverse:
 [[-1.    0.5 ]
 [ 0.75 -0.25]]
B⁻¹ A⁻¹:
 [[-1.    0.5 ]
 [ 0.75 -0.25]]


## Inverse of Transpose.


- (A ^ T ) ^ - 1 = (A ^ - 1) ^ T

In [12]:
A = np.array([[2, 1], [5, 3]])
A_T_inv = inv(A.T)
A_inv_T = inv(A).T
print("Transpose then inverse:\n", A_T_inv)
print("Inverse then transpose:\n", A_inv_T)  # Should match


Transpose then inverse:
 [[ 3. -5.]
 [-1.  2.]]
Inverse then transpose:
 [[ 3. -5.]
 [-1.  2.]]


## Solving Linear Systems(Ax = b) in Linear Algebra in SciPy.

- In Linear Algebra  :  A is a known matrix (size n×n),  x is a column vector of unknowns (what we want to find) and b is another known vector(the output).

- We are solving the equation  :  Ax=b, This means we want to find the values in vector x that, when multiplied by matrix A, give vector b.

- You can solve Ax = b when  :  Matrix A is square(same number of rows and columns), A is invertible(its determinant is not zero).

- If A is singular (determinant = 0), there's  :  No unique solution or infinitely many solutions.

- If A is upper or lower triangular (all zeros above or below diagonal), it's faster to use.

In [15]:
# Example  :  2x + 3y = 8 and  3x + 4y = 11.

import numpy as np
from scipy.linalg import solve

A = np.array([[2, 3], [3, 4]])
b = np.array([8, 11])
x = solve(A, b)
print("Solution:", x)  # This gives values for x and y



Solution: [1. 2.]


## Features of Solving Linear Systems(Ax = b).

## Solves for Unknown Variables Efficiently.

- The main purpose of solving Ax=b is to find the values of unknown variables in a System of equations.

In [16]:
import numpy as np
from scipy.linalg import solve

A = np.array([[2, 3], [1, 2]])
b = np.array([8, 5])
x = solve(A, b)
print("Solution x:", x)


Solution x: [1. 2.]


## More Accurate Than Inverting A.

- Instead of doing x = A^ - 1. b, which can be numerically unstable, solve() uses smarter methods(like LU decomposition) Internally.

In [17]:
from numpy.linalg import inv

# Not recommended:
x1 = inv(A) @ b
# Better:
x2 = solve(A, b)
print("Accurate solution:", x2)


Accurate solution: [1. 2.]


## Handles Multiple Right-Hand Sides.

- You can solve systems like  AX=B, where B contains multiple b vectors.

In [19]:
B = np.array([[8, 6], [5, 7]])
X = solve(A, B)
print("Multiple solutions:\n", X)


Multiple solutions:
 [[ 1. -9.]
 [ 2.  8.]]


## Faster for Triangular Matrices.

-  If A is triangular(e.g. in LU decomposition), you can use solve_triangular() for faster results.

In [20]:
from scipy.linalg import solve_triangular

U = np.array([[3, 2], [0, 4]])
b = np.array([9, 8])
x = solve_triangular(U, b)
print("Triangular system solution:", x)


Triangular system solution: [1.66666667 2.        ]


## Deteminant of the Matrix in Linear Algebra in SciPy.


- The determinant is a single number that is calculated from a square matrix (like 2×2, 3×3, etc.). It tells us certain important properties about that matrix.

- If the determinant is not zero, the matrix is invertible(it has an inverse) and If the determinant is zero, the matrix is singular (no inverse exists).

- The identity matrix doesn’t change anything, so its determinant is always 1.



In [22]:
# Example 1 : Determinant of the Matrix of 2 * 2 Matrix.

from scipy.linalg import det
import numpy as np

A = np.array([[2, 3], [1, 4]])
print(det(A))  


5.0


In [24]:
# Example 2: Invertible Matrix.

import numpy as np
from scipy.linalg import det

# Example 1: Invertible Matrix
A = np.array([[2, 3], [1, 4]])
dA = det(A)
print("Matrix A:")
print(A)
print("Determinant of A:", dA)
if dA != 0:
    print("A is invertible.\n")
else:
    print("A is non-invertible (singular).\n")


# Non-Invertible Matrix.
B = np.array([[1, 2], [2, 4]])
dB = det(B)
print("Matrix B:")
print(B)
print("Determinant of B:", dB)
if dB != 0:
    print("B is invertible.\n")
else:
    print("B is non-invertible (singular).\n")

Matrix A:
[[2 3]
 [1 4]]
Determinant of A: 5.0
A is invertible.

Matrix B:
[[1 2]
 [2 4]]
Determinant of B: 0.0
B is non-invertible (singular).



In [25]:
# Example 3 : Determinant of Identity Matrix is 1.

I = np.eye(3)
print(det(I))  # 1.0


1.0


## Features of Determinant of a Matrix.

## Works Only with Square Matrices.

- The determinant is only defined for square matrices (same number of rows and columns), like 2×2, 3×3, etc.

In [26]:
import numpy as np
from scipy.linalg import det

A = np.array([[1, 2], [3, 4]])  # 2x2 (OK)
print("Determinant:", det(A))  # Output: -2.0

B = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3 (Not square)
# print(det(B))  # Uncommenting this will raise an error


Determinant: -2.0


## Tells Whether a Matrix is Invertible.


- If the Determinant is not Zero, the Matrix is Invertible(has an Inverse). If it's zero, the Matrix is Singular(not Invertible).

In [27]:
C = np.array([[2, 4], [1, 2]])  # Singular matrix
print("Determinant:", det(C))  # Output: 0.0 → not invertible


Determinant: 0.0


## Result can Be Positive, Negative, or Zero.



In [31]:
import numpy as np
from scipy.linalg import det

A = np.array([[1, 2], [3, 4]])  # 2x2 (OK)
print("Determinant:", det(A))  # Output: -2.0

from scipy.linalg import det
import numpy as np

A = np.array([[2, 3], [1, 4]])  # Output: 5.0
print(det(A))  


from scipy.linalg import det
import numpy as np

A = np.array([[2, 2], [2, 2]])  # Output: 0.0
print(det(A))  


Determinant: -2.0
5.0
0.0


## Multiplying a Row by a Scalar Multiplies the Determinant.


- If you multiply one row of a matrix by k, the determinant is also multiplied by k.



In [32]:
G = np.array([[1, 2], [3, 4]])
G_scaled = np.array([[1, 2], [6, 8]])  # Row 2 multiplied by 2
print(det(G))         # Output: -2.0
print(det(G_scaled))  # Output: -4.0 → doubled


-2.0
-4.0


## Swapping Rows Changes the Sign.

- If you swap two rows, the sign of the determinant flips.

In [33]:
H1 = np.array([[1, 2], [3, 4]])
H2 = np.array([[3, 4], [1, 2]])  # Swapped rows
print(det(H1))  # -2.0
print(det(H2))  # +2.0 (flipped sign)


-2.0
2.0


### Used in System of Equations.

- In solving Ax = b, if det(A) = 0, the system has no unique solution. If det(A) ≠ 0, then it has a unique solution.

In [34]:
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
# Since det(A) ≠ 0, solution exists
from scipy.linalg import solve
x = solve(A, b)
print("Solution x:", x)


Solution x: [-4.   4.5]


## Zero Determinant Implies Linear Dependence.

- If any row/column is a linear combination of others, determinant = 0.

In [35]:
N = np.array([[2, 4], [1, 2]])  # Row 2 = 0.5 × Row 1
print("Determinant:", det(N))  # 0.0 → linearly dependent


Determinant: 0.0


## Can Be Used to Compute Area or Volume.

- In geometry, for 2D or 3D vectors, the determinant can represent area or volume of parallelograms and parallelepipeds.

In [36]:
# Area of parallelogram formed by vectors
v1 = [2, 0]
v2 = [0, 3]
M = np.column_stack((v1, v2))
print("Area of parallelogram:", abs(det(M)))  # 6.0


Area of parallelogram: 6.0


## LU Decomposition in Linear Algebra in SciPy.

- LU decomposition factors a square matrix A into the product of two (or three) simpler matrices i.e. A = P. LU.

- P — a permutation matrix (captures any row swaps performed for numerical stability).


- L — a unit lower-triangular matrix (ones on its diagonal, non-zero values only below the diagonal).

- U — an upper-triangular matrix (non-zero entries only on/above the diagonal).

In [1]:
import numpy as np
from scipy.linalg import lu

A = np.array([[4, 3], [6, 3]])
P, L, U = lu(A)

print("P =\n", P)
print("L =\n", L)
print("U =\n", U)


P =
 [[0. 1.]
 [1. 0.]]
L =
 [[1.         0.        ]
 [0.66666667 1.        ]]
U =
 [[6. 3.]
 [0. 1.]]


## Permutation Matrix(P).

- P accounts for row swaps needed to make LU decomposition stable. It’s an identity matrix with reordered rows.

In [2]:
# Verifying the decomposition.

print("Original A =\n", A)
print("P @ A =\n", np.dot(P, A))
print("L @ U =\n", np.dot(L, U))


Original A =
 [[4 3]
 [6 3]]
P @ A =
 [[6. 3.]
 [4. 3.]]
L @ U =
 [[6. 3.]
 [4. 3.]]


## Solving Linear Systems using LU.


- Once A is decomposed, solving Ax = b becomes easier by solving two triangular systems: Solve Ly = Pb and then solve Ux = y.



In [3]:
from scipy.linalg import lu_factor, lu_solve

b = np.array([10, 12])
lu_fact = lu_factor(A)
x = lu_solve(lu_fact, b)

print("Solution x =", x)


Solution x = [1. 2.]


## Checking LU Decomposition Accuracy.


- We can verify if LU decomposition was done correctly by checking if  : P . A = L.U.

In [4]:
import numpy as np
from scipy.linalg import lu

# Example 1 ── simple 3×3 integer matrix
A = np.array([[2, 1, 3],
              [4, 1, 6],
              [2, 5, 1]])

P, L, U = lu(A)

print("P·A =\n", P @ A)
print("L·U =\n", L @ U)
print("LU accurate?", np.allclose(P @ A, L @ U))


P·A =
 [[2. 5. 1.]
 [2. 1. 3.]
 [4. 1. 6.]]
L·U =
 [[4. 1. 6.]
 [2. 5. 1.]
 [2. 1. 3.]]
LU accurate? False


## QR Decomposition in Linear Algebra in SciPy .


- It is the Process of breaking a Matrix A into  :  Q  : A Matrix with Orthonormal Columns  and  R : A Matrix that is Upper Triangular, so that A = Q . R.

- An Orthogonal Matrix(Q) is a Square Matrix whose Columns(and Rows) are Orthonormal Vectors — meaning : Each column has a length of 1, Columns are at 90° (perpendicular) to each other.

- Mathematically   :  Q ^ T . Q = I.

- Transpose = Inverse  :  A Key Property of Orthogonal Matrices is  : Q  ^ T = Q ^ - 1 i.e. This means multiplying by Q^T is the same as inverting Q.

- Square or Rectangular :  If A is Square, Q is Square and If A is Rectangular, Q still has Orthonormal Columns but may not be Square.

- An Upper - Triangular Matrix(R) is a matrix where all values below the Main Diagonal are Zero.

- If A is an m x n Matrix  :  R will be n x n and Upper - Triangular.

  



In [5]:
# Example 1 : Basic Example of QR Decomposition.

import numpy as np
from scipy.linalg import qr

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

Q, R = qr(A)
print("Q:\n", Q)
print("R:\n", R)


Q:
 [[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
R:
 [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


In [6]:
# Example 2  : An Orthogonal Matrix i.e. Q.

import numpy as np
from scipy.linalg import qr

# Define a real matrix
A = np.array([[1, 2],
              [3, 4]])

# Perform QR decomposition
Q, R = qr(A)

# Print Q
print("Orthogonal Matrix Q:")
print(Q)

# Check if Q.T @ Q == I (identity)
identity_check = np.allclose(Q.T @ Q, np.eye(Q.shape[1]))
print("\nIs Q orthogonal (Q.T @ Q == I)?", identity_check)


Orthogonal Matrix Q:
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]

Is Q orthogonal (Q.T @ Q == I)? True


## Helps Solve Linear Systems.


- QR is used to solve Equations like A.x = b by Transforming it into an Easier Triangular form.



In [7]:
from scipy.linalg import solve_triangular

b = np.array([5, 11])
y = Q.T @ b
x = solve_triangular(R, y)
print("Solution x:", x)


Solution x: [1. 2.]


## Eigenvalues and Eigenvectors in Linear Algebra in SciPy.

## Eigenvalues.


- An Eigenvalue is a Scalar(a Number) that tells how much a Vector gets Stretched or Compressed when a Matrix Transforms it.

- If you multiply a square matrix A with a vector x, and the result is just a scaled version of x, then the scalar is the eigenvalue.

- Equation      :  A . x  =  λ . x.

- Here, A is a Matrix, x is an Eigenvector and  λ is the Eigenvalue.

## Features of Eigenvalues.

## Only Square Matrices Have Eigenvalues. 

- You can only Calculate Eigenvalues for Square Matrices(like 2x2, 3x3, etc.).



In [2]:
import numpy as np
from scipy.linalg import eig

A = np.array([[4, 2],
              [1, 3]])
values, vectors = eig(A)
print("Eigenvalues:", values)


Eigenvalues: [5.+0.j 2.+0.j]


## Each Eigenvalue has an Eigenvector.

- Each Eigenvalue has a Corresponding Eigenvector that shows the Direction of Transformation.

In [9]:
print("Eigenvector for first eigenvalue:\n", vectors[:, 0])
print("Eigenvalue 1:", values[0])


Eigenvector for first eigenvalue:
 [0.89442719 0.4472136 ]
Eigenvalue 1: (5+0j)


## Eigenvalues can Be Complex Numbers.


- If a Matrix has certain kinds of Symmetries or Rotations, it's Eigenvalues may be Complex(have an Imaginary Part).

In [10]:
B = np.array([[0, -1],
              [1,  0]])
vals, vecs = eig(B)
print("Eigenvalues (may be complex):", vals)


Eigenvalues (may be complex): [0.+1.j 0.-1.j]


## Eigenvalues are Found from the Characteristic Equation.


- Eigenvalues are Roots of the Characteristic Equation  :  det(A−λI)=0   i.e. This equation is solved to find the values of λ.
  

In [12]:
# Just a demo using NumPy for det().


from numpy.linalg import det
I = np.eye(2)
λ = 2  # Try a value
print("det(A - λI):", det(A - λ * I))


det(A - λI): 0.0


## Eigenvalues of Symmetric Matrices Are Always Real.

- For Symmetric Matrices(where A = Aᵗ), all Eigenvalues are Real Numbers.

In [13]:
C = np.array([[2, 1], [1, 2]])
vals, _ = eig(C)
print("Real eigenvalues of symmetric matrix:", vals)


Real eigenvalues of symmetric matrix: [3.+0.j 1.+0.j]


##  The Sum of Eigenvalues Equals the Trace.

- The Trace of a Matrix(Sum of its Diagonal Elements) equals the Sum of its Eigenvalues.

In [14]:
A = np.array([[2, 1], [1, 3]])
vals, _ = eig(A)
print("Trace:", np.trace(A), "| Sum of eigenvalues:", np.sum(vals))
B = np.array([[5, 0], [0, 1]])
vals2, _ = eig(B)
print("Trace match:", np.isclose(np.trace(B), np.sum(vals2)))


Trace: 5 | Sum of eigenvalues: (5+0j)
Trace match: True


## The Product of Eigenvalues Equals the Determinant.

In [15]:
A = np.array([[3, 1], [0, 2]])
vals, _ = eig(A)
print("Determinant:", np.linalg.det(A), "| Product of eigenvalues:", np.prod(vals))
B = np.array([[1, 2], [3, 4]])
vals2, _ = eig(B)
print("Det match:", np.isclose(np.linalg.det(B), np.prod(vals2)))


Determinant: 6.0 | Product of eigenvalues: (6+0j)
Det match: True


## Eigenvectors in SciPy.


- A Non - Zero Vector v is an Eigenvector of a Square Matrix A if Multiplying A by v Simply Stretches(or flips) it, i.e. A @ v = λ * v, where λ(Lambda) is the Matching Eigenvalue.

- Eigenvectors exist only for Square(n × n) Matrices.



In [3]:
# Example : Basic Example of Eigenvectors in SciPy.

A = np.array([[4, 2],
              [1, 3]])
eig_vals, eig_vecs = eig(A)           # columns of eig_vecs are eigenvectors
print("λ:", eig_vals[0])
print("v:", eig_vecs[:, 0])
print("A @ v:", A @ eig_vecs[:, 0])   # should equal λ * v


λ: (5+0j)
v: [0.89442719 0.4472136 ]
A @ v: [4.47213595 2.23606798]


In [5]:
# Example : Eigenvectors exist only for Square(n × n) Matrices.

square_ok = eig(np.eye(3))            # succeeds
# eig(np.ones((2,3)))  # would raise an error (non-square)


## Features of Eigenvectors.

## Eigenvectors of Symmetric Matrices are Orthogonal.

-  For Symmetric Matrices(A = Aᵀ), Eigenvectors corresponding to different Eigenvalues are Perpendicular.

In [6]:
C = np.array([[3, 2], [2, 3]])
w_c, v_c = eig(C)
dot = np.dot(v_c[:, 0].real, v_c[:, 1].real)
print("Dot product (should be ~0):", dot)
print("v1:", v_c[:, 0].real)
print("v2:", v_c[:, 1].real)


Dot product (should be ~0): 2.237114317075737e-17
v1: [0.70710678 0.70710678]
v2: [-0.70710678  0.70710678]


## Eigenvectors Point in Invariant Directions.

- An Eigenvector of a Matrix shows the direction that does not change when a Matrix is Applied. The vector may get stretched or shrunk (scaled), but its direction remains the same.



In [7]:
import numpy as np
from scipy.linalg import eig

A = np.array([[2, 1], [1, 2]])
w, v = eig(A)
print("Eigenvectors:\n", v)

x = v[:, 0]
print("A @ x:", A @ x)
print("w[0] * x:", w[0] * x)  # Direction remains the same


Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
A @ x: [2.12132034 2.12132034]
w[0] * x: [2.12132034+0.j 2.12132034+0.j]


## Eigenvectors are Not Unique in Magnitude.

-  Eigenvectors are defined up to a Scalar Multiple. This means if v is an Eigenvector, so is 2v, -3v, etc.

In [8]:
print("Original vector:\n", v[:, 0])
print("Scaled vector:\n", 3 * v[:, 0])
# Check both still satisfy Av = λv
print("A @ (3v):", A @ (3*v[:,0]))
print("λ*(3v):", w[0]*(3*v[:,0]))


Original vector:
 [0.70710678 0.70710678]
Scaled vector:
 [2.12132034 2.12132034]
A @ (3v): [6.36396103 6.36396103]
λ*(3v): [6.36396103+0.j 6.36396103+0.j]


## Eigenvectors can Be Real or Complex.


- Real Matrices can have complex Eigenvectors, especially when they represent Rotation or Oscillation.

In [10]:
B = np.array([[0, -1], [1, 0]])
w_b, v_b = eig(B)
print("Eigenvalues:", w_b)
print("Eigenvectors:\n", v_b)
print("A @ v_b[0]:", B @ v_b[:, 0])
print("λ * v_b[0]:", w_b[0] * v_b[:, 0])


Eigenvalues: [0.+1.j 0.-1.j]
Eigenvectors:
 [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]
A @ v_b[0]: [0.        +0.70710678j 0.70710678+0.j        ]
λ * v_b[0]: [0.        +0.70710678j 0.70710678+0.j        ]


## Eigenvectors are Sensitive to Matrix Changes.

- Slight changes in the Matrix can cause large changes in Eigenvectors, especially when Eigenvalues are nearly equal.

In [11]:
A1 = np.array([[2, 1], [1, 2]])
A2 = np.array([[2, 1.001], [1.001, 2]])
w1, v1 = eig(A1)
w2, v2 = eig(A2)
print("Direction change?\n", v1[:, 0], "\n", v2[:, 0])


Direction change?
 [0.70710678 0.70710678] 
 [0.70710678 0.70710678]


## Singular Value Decomposition(SVD) in Linear Algebra in SciPy.


- SVD(Singular Value Decomposition) breaks down a Matrix A into Three Matrices  :  A = U × Σ × Vᵀ, where:
- U is a matrix with left singular vectors (orthogonal),
- Σ (Sigma) is a diagonal matrix with singular values,
- Vᵀ is the transpose of the matrix with Right Singular Vectors(also Orthogonal).

In [13]:
# Example  :  Basic Example of Singular Value Decomposition(SVD).

import numpy as np
from scipy.linalg import svd

A = np.array([[1, 2], [3, 4]])
U, S, VT = svd(A)
print("U:\n", U)
print("Singular Values:\n", S)
print("V Transpose:\n", VT)


U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular Values:
 [5.4649857  0.36596619]
V Transpose:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


## Features of Singular Value Decomposition(SVD).

## Universally Applicable.

- SVD works on all Real and Complex Matrices, regardless of Shape or Rank.

In [14]:
A = np.array([[1, 2], [3, 4], [5, 6]])
U, S, VT = svd(A)
print("U shape:", U.shape, "S:", S, "V^T shape:", VT.shape)


U shape: (3, 3) S: [9.52551809 0.51430058] V^T shape: (2, 2)


## Works for any Matrix.

- Unlike eigendecomposition, which only works for square matrices, SVD works for any shape matrix – square or rectangular


In [15]:
A = np.array([[1, 2, 3], [4, 5, 6]])
U, S, VT = svd(A)
print("Shape of A:", A.shape)


Shape of A: (2, 3)


## U and V are Orthogonal Matrices.

- U and V (after transposing V to V^T) are Orthogonal, meaning their Columns are Perpendicular and have Unit Length.

In [16]:
print("U.T @ U ≈ I:\n", np.round(U.T @ U, 2))
print("VT @ VT.T ≈ I:\n", np.round(VT @ VT.T, 2))


U.T @ U ≈ I:
 [[ 1. -0.]
 [-0.  1.]]
VT @ VT.T ≈ I:
 [[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]]


## Matrix Exponential in Linear Algebra in SciPy.


- The Matrix Exponential is a way to extend the Exponential Function to Matrices. For a Square Matrix A, the Exponential exp(A) is defined using a Power Series, similar to how e^x is defined for Numbers.


- Formula  =   exp(A) = I + A + A²/2! + A³/3! + ... (where I is the Identity Matrix).


In [17]:
# Example : Basic Example of Matrix Exponential.

import numpy as np
from scipy.linalg import expm
A = np.array([[0, 1], [-2, -3]])
print("Matrix Exponential:\n", expm(A))


Matrix Exponential:
 [[ 0.6004236   0.23254416]
 [-0.46508832 -0.09720887]]


## Features of Matrix Exponential.

## Works on any Square Matrix.

- The Matrix must be Square(Same Number of Rows and Columns). It can have any Values.



In [19]:
A = np.array([[2, -1], [1, 0]])
print(expm(A))


[[ 5.43656366e+00 -2.71828183e+00]
 [ 2.71828183e+00 -6.66133815e-16]]


## Solves Systems of the Form dx/dt = Ax.

- You can find how a system evolves over Time without Solving Differential Equations manually.


In [21]:
# Solve x(t) = expm(A*t) @ x0.

A = np.array([[0, 1], [-1, -2]])
x0 = np.array([1, 0])
t = 2
x_t = expm(A*t) @ x0
print("x(t):", x_t)


x(t): [ 0.40600585 -0.27067057]


# Exponential of Identity Matrix is e×I.

In [25]:
# Exponential of Identity Matrix is e×I.

I = np.eye(3)
print(expm(I))  # returns e * I


[[2.71828183 0.         0.        ]
 [0.         2.71828183 0.        ]
 [0.         0.         2.71828183]]


##  Different from Element-wise Exponential.

- Do not confuse expm(A) with np.exp(A) which applies the Exponential to each Element of A.

In [26]:
print("Matrix Exponential:\n", expm(A))
print("Element-wise Exponential:\n", np.exp(A))  # not the same


Matrix Exponential:
 [[ 7.35758882e-01  3.67879441e-01]
 [-3.67879441e-01  2.22044605e-16]]
Element-wise Exponential:
 [[1.         2.71828183]
 [0.36787944 0.13533528]]


## Result is a New Matrix.

- The result of expm(A) is a Matrix of the Same Size, but Transformed using the Matrix Exponential.



In [27]:
A = np.array([[0, 1], [-2, -3]])
expA = expm(A)
print("Shape:", expA.shape)
print(expA)


Shape: (2, 2)
[[ 0.6004236   0.23254416]
 [-0.46508832 -0.09720887]]


## Cholesky Decomposition in Linear Algebra in SciPy.

- Cholesky Decomposition is a Special Kind of Matrix Factorization used mostly when the Matrix is Symmetric and Positive - Definite. It breaks a Matrix A into two simpler matrices: a lower triangular matrix L and its transpose L.T.

  
- It follows this Form  :   A  =  L . L ^ T, Where :  A is a Symmetric, Positive - Definite Matrix and L is a Lower -  Triangular Matrix
 


## Features of Cholesky Decomposition.


## Used Only on Symmetric Positive-Definite Matrices.

- A Matrix A must satisfy :  Symmetry  :  A = A.T Positive - Definiteness: All Eigenvalues > 0(or x.T @ A @ x > 0 for all non-zero x).

In [28]:
import numpy as np
from scipy.linalg import cholesky

A = np.array([[4, 2], [2, 3]])
L = cholesky(A, lower=True)
print("L:\n", L)


L:
 [[2.         0.        ]
 [1.         1.41421356]]


# Faster and More Stable Than LU for SPD Matrices.

- Cholesky is about Twice as fast as LU Decomposition and numerically more stable for these types of Matrices.

## Returns Lower or Upper Triangular Matrix.

- You can choose  :  lower=True for L such that A = L @ L.T or lower=False for upper triangular U, where A = U.T @ U.

In [29]:
U = cholesky(A, lower=False)
print("U:\n", U)


U:
 [[2.         1.        ]
 [0.         1.41421356]]


## Can be Used to Solve Linear Systems.

- If A = L @ L.T, and you want to solve Ax = b, you can  :  Solve L @ y = b for y and  Solve L.T @ x = y for x.

In [31]:
from scipy.linalg import solve_triangular

b = np.array([6, 5])
y = solve_triangular(L, b, lower=True)
x = solve_triangular(L.T, y, lower=False)
print("Solution x:\n", x)
print("Solution y:\n", y)


Solution x:
 [1. 1.]
Solution y:
 [3.         1.41421356]


## Singular Matrix in Linear Algebra in SciPy.


- A singular Matrix is a Square Matrix that cannot be Inverted.

- It has To check if a matrix is singular, we test its Determinant, Rank, or Invertibility.

- If det(A) == 0, the Matrix is Singular.

- If rank(A) < n (for n×n matrix), then it’s singular.

- Trying to compute inv(A) in NumPy/SciPy will raise an error if singular.

- SciPy does not have a direct is_singular function but provides tools to test it.

- Use scipy.linalg.det() or np.linalg.det() for determinant.

- Use np.linalg.matrix_rank() to check rank of matrix.

- Use scipy.linalg.cond() to check condition number: very large value → near-singular.

- Use np.allclose(A @ invA, I) to verify invertibility (if invA exists).

- Near-zero eigenvalues can also signal singularity or instability.

- For symbolic checks, use SymPy; for numerical, prefer NumPy/SciPy.

- These checks are useful in regression, optimization, and simulations.Determinant = 0, which means it Collapses space in some direction.

- It's rows or columns are Linearly Dependent.

- Singular matrices do not have full rank (rank < number of rows).

- When used in solving Ax = b, they may lead to infinite or no solutions.

- Common causes: duplicate rows, zero rows, or any form of linear redundancy.

- In numerical methods, singular matrices cause errors or instability.

- Many algorithms like LU or Cholesky fail or raise errors when matrix is singular.

- SciPy and NumPy provide functions to check singularity and handle it.

- Singular matrices appear in applications like underdetermined systems or bad modeling.

- Pseudo-inverses (like np.linalg.pinv) are used when inversion is not possible.

- Detecting singularity is essential in Machine Learning, Simulation, and Linear Algebra.



In [32]:
# Example : Basic Example of Singular Matrix i.e. Checking whether the Matrix is Singular Matrix or not using Finding the Determinant in Linear Algebra in SciPy.

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [1, 2, 3]])  # Row 1 and 3 are identical → singular
print("Determinant:", np.linalg.det(A))  # Outputs: 0.0


Determinant: 0.0


In [33]:
# Example : Basic Example of Singular Matrix i.e. Checking whether the Matrix is Singular Matrix or not using np.linalg.det in Linear Algebra in SciPy.

import numpy as np
from scipy.linalg import det

A = np.array([[1, 2], [2, 4]])
print("Is Singular:", det(A) == 0)  # True


Is Singular: True


In [35]:
# Example : Basic Example of Singular Matrix i.e. Checking whether the Matrix is Singular Matrix or not using Matrix Rank in Linear Algebra in SciPy.

from numpy.linalg import matrix_rank

A = np.array([[1, 2], [2, 4]])
print("Rank:", matrix_rank(A))     # Outputs: 1 (for 2x2 → singular)


Rank: 1
