## Universal Functions in SciPy.


- Universal Functions (ufuncs) are functions that operate element-wise on arrays. They perform vectorized operations that are fast and efficient.

- Ufuncs are provided by NumPy, but are heavily used in SciPy functions and scientific computations because they’re optimized for performance.

- They perform operations on each element individually without the need for explicit loops.

- Ufuncs work with arrays of different shapes using broadcasting rules to align dimensions.

- Ufuncs automatically handle type conversion when combining different data types.

- They are implemented in C, making them much faster than Python loops for large data.

- Some ufuncs can take multiple input arrays and return multiple outputs.

- Ufuncs cover a wide range of math operations: addition, subtraction, multiplication, division, power, etc.

- Ufuncs include logical, bitwise, and comparison operations.

- They include scientific functions like trigonometry, exponential, and logarithmic functions.

- Ufuncs have support to handle NaN (Not a Number) and infinity in computations.

- You can define your own ufunc using np.vectorize() or np.frompyfunc().

  

In [1]:
#1) Definition of Universal Functions in SciPy.


import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.add(a, b))  # Output: [5 7 9]




[5 7 9]


In [2]:
#2) NumPy-backed in SciPy.


from scipy import special

x = np.array([0, 1, 2])
print(special.exp10(x))  # Output: [  1.  10. 100.]


[  1.  10. 100.]


In [3]:
#3) Element-wise Execution.

a = np.array([1, 4, 9])
print(np.sqrt(a))  # Output: [1. 2. 3.]


[1. 2. 3.]


In [4]:
#4)  Broadcasting Support.


a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
print(np.add(a, b))
# Output: [[11 22]
#          [13 24]]


[[11 22]
 [13 24]]


In [5]:
#5)  Type Casting.

a = np.array([1, 2, 3], dtype=int)
b = np.array([1.5, 2.5, 3.5], dtype=float)
print(np.add(a, b))  # Output: [2.5 4.5 6.5] (float result)


[2.5 4.5 6.5]


In [6]:
#6)  Performance Optimization.


# Using vectorized ufunc is faster than loops
a = np.arange(1e6)
b = np.arange(1e6)
result = np.add(a, b)  # Fast and efficient


In [7]:
#7)  Multiple Inputs and Outputs.


a = np.array([2, 3])
b = np.array([5, 2])
quotient, remainder = np.divmod(a, b)
print(quotient)   # Output: [0 1]
print(remainder)  # Output: [2 1]


[0 1]
[2 1]


In [8]:
#8) Mathematical Operations in SciPy.

a = np.array([2, 3, 4])
print(np.power(a, 2))  # Output: [ 4  9 16]


[ 4  9 16]


In [9]:
#9)  Logical and Comparison Functions.


a = np.array([1, 2, 3])
b = np.array([3, 2, 1])
print(np.greater(a, b))  # Output: [False False  True]


[False False  True]


In [10]:
#10)  Trigonometric and Exponential Functions.


angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))  # Output: [0. 1. 0.]


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [12]:
#11)  Handling Special Values(NaN, inf).


a = np.array([1, 0, np.nan])
b = np.array([0, 0, 2])
result = np.divide(a, b)
print(result)  # Output: [inf nan nan]


[inf nan nan]


C:\Users\abhis\AppData\Local\Temp\ipykernel_12868\2002724264.py:6: RuntimeWarning: divide by zero encountered in divide
  result = np.divide(a, b)
C:\Users\abhis\AppData\Local\Temp\ipykernel_12868\2002724264.py:6: RuntimeWarning: invalid value encountered in divide
  result = np.divide(a, b)


In [13]:
#12)  Custom Universal Functions.

def square(x):
    return x * x

vfunc = np.vectorize(square)
arr = np.array([1, 2, 3])
print(vfunc(arr))  # Output: [1 4 9]


[1 4 9]


## Features of Universal Functions in SciPy.


## Element-wise Operations.


- Ufuncs operate on each element individually in arrays, without requiring explicit loops.

In [14]:
import numpy as np

a = np.array([1, 2, 3])
print(np.square(a))  # Output: [1 4 9]


[1 4 9]


## Vectorized Execution(No Loops Needed).

- Ufuncs use vectorization, leading to faster execution compared to Python loops.

In [16]:
a = np.arange(1000000)
result = np.sqrt(a)  # Fast vectorized computation.
print(result)


[  0.           1.           1.41421356 ... 999.9985     999.999
 999.9995    ]


## Supports Broadcasting.

- Ufuncs automatically broadcast smaller arrays to match the shape of larger ones.


In [17]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
print(np.add(a, b))
# Output:
# [[11 22]
#  [13 24]]


[[11 22]
 [13 24]]


## Handles Multiple Inputs.


- Many ufuncs accept two or more input arrays, performing operations pairwise.

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.multiply(a, b))  # Output: [ 4 10 18]


[ 4 10 18]


##  Multiple Outputs Support.


- Some ufuncs return more than one output, useful for simultaneous calculations.

In [19]:
a = np.array([10, 20])
b = np.array([3, 4])
quotient, remainder = np.divmod(a, b)
print(quotient)   # [3 5]
print(remainder)  # [1 0]


[3 5]
[1 0]


## Data Type Flexibility & Promotion.

- Ufuncs handle different data types intelligently and return a suitable output type.


In [20]:
a = np.array([1, 2], dtype=int)
b = np.array([1.5, 2.5], dtype=float)
print(np.add(a, b))  # Output: [2.5 4.5] → float output


[2.5 4.5]


## Logical and Bitwise Operation Support.

- Ufuncs include Logical(Logical_and, Greater) and Bitwise(Bitwise_and) Operations.


In [21]:
a = np.array([True, False, True])
b = np.array([False, False, True])
print(np.logical_and(a, b))  # Output: [False False  True]


[False False  True]


## Trigonometric, Exponential, and Logarithmic Support.


- Ufuncs support scientific functions like trigonometry, exponentials, and logs.

In [22]:
angles = np.array([0, np.pi / 2, np.pi])
print(np.sin(angles))  # Output: [0. 1. 0.]


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [23]:
x = np.array([1, np.e, np.e**2])
print(np.log(x))    # Natural log
print(np.exp(x))    # Exponential function


[0. 1. 2.]
[   2.71828183   15.15426224 1618.17799191]


## Supports Basic Arithmetic Operations.

- Ufuncs allow simple arithmetic operations like Addition, Subtraction, Multiplication, and Division between Arrays.




In [24]:
import numpy as np

a = np.array([2, 4, 6])
b = np.array([1, 2, 3])

print(np.add(a, b))       # [3 6 9]
print(np.subtract(a, b))  # [1 2 3]
print(np.multiply(a, b))  # [2 8 18]
print(np.divide(a, b))    # [2. 2. 2.]


[3 6 9]
[1 2 3]
[ 2  8 18]
[2. 2. 2.]


## Supports Power and Modulus Operations.


- You can raise array elements to powers or get remainders using np.power() and np.mod().

In [25]:
a = np.array([2, 3, 4])
b = np.array([3, 2, 1])

print(np.power(a, b))  # [8 9 4]
print(np.mod(a, b))    # [2 1 0]


[8 9 4]
[2 1 0]


## Supports Absolute Value and Negative Operations.


- Ufuncs like np.abs() and np.negative() provide element-wise transformation.

In [26]:
a = np.array([-1, -2, 3])

print(np.abs(a))       # [1 2 3]
print(np.negative(a))  # [1 2 -3]


[1 2 3]
[ 1  2 -3]


## Supports Reciprocal and Sign Functions.

- Useful for numerical operations: np.reciprocal() gives inverse, np.sign() shows the sign of each number.



In [27]:
a = np.array([1, -2, 0])

print(np.reciprocal([1., 2., 0.5]))  # [1. 0.5 2.]
print(np.sign(a))                   # [ 1 -1  0]


[1.  0.5 2. ]
[ 1 -1  0]


## Supports Rounding and Truncation in Numbers.


- Use ufuncs to control number formats — np.floor(), np.ceil(), np.trunc(), etc.

In [28]:
a = np.array([1.7, -1.2, 0.5])

print(np.floor(a))  # [ 1. -2.  0.]
print(np.ceil(a))   # [ 2. -1.  1.]
print(np.trunc(a))  # [ 1. -1.  0.]


[ 1. -2.  0.]
[ 2. -1.  1.]
[ 1. -1.  0.]


## Supports Arithmetic with Mixed Data -  Types.


- Ufuncs automatically promote types (int → float → complex) for consistent output.

In [29]:
a = np.array([1, 2], dtype=int)
b = np.array([1.5, 2.5], dtype=float)

print(np.add(a, b))  # [2.5 4.5]


[2.5 4.5]
