## Array indexing and Array Slicing in SciPy.

## Array Indexing in SciPy.


- Array Indexing means accessing individual elements or groups of elements in an array using their position (index).

- SciPy uses NumPy arrays, so array indexing in SciPy is exactly the same as in NumPy.

- You can use integer indexing to access one element (e.g., arr[0]).

- You can use multi-dimensional indexing for 2D or higher arrays (e.g., arr[1, 2]).

- You can combine slicing and indexing together (e.g., arr[1, :2]).

- You can use boolean indexing to filter values based on a condition (e.g., arr[arr > 5]).

- You can use fancy indexing with arrays/lists of index values (e.g., arr[[0, 2, 4]]).

- Indexing allows efficient and fast access to parts of data without copying it.

- Indexing supports negative indices (e.g., arr[-1] gives last item).

- It’s the foundation for data selection, manipulation, filtering, and modifying array content.

- Indexing supports both reading and writing operations.

- Indexing is very useful in machine learning, image processing, and scientific computing.

- Indexing allows direct access to elements for computation or modification.

- Essential for data preprocessing in scientific and numerical tasks.

- Enables condition-based selection (e.g., filtering data above a threshold).

- Helps in loop-less vectorized operations, which are faster.

- Makes matrix operations easier and more readable.

- Allows efficient memory usage, as it often returns views.

- Helps with image and signal processing, common in SciPy.

- Simplifies working with multi-dimensional data like 2D/3D matrices.

- Useful in tasks like row/column extraction, flattening, etc.

- Greatly improves code clarity and speed in large-scale data computations.

- Supports multi-dimensional indexing (1D, 2D, 3D…).

- Boolean indexing allows filtering using conditions.

- Fancy indexing allows accessing multiple indices at once.

- Negative indexing lets you count from the end.

- Indexing creates a view, not a copy (efficient).

- Can be used to modify original data in-place.

- Works with logical masks to filter elements.

- Easy combination with slicing.

- Compatible with SciPy functions (e.g., interpolation, stats).

- Supports broadcasting with indexing for vectorized updates.

- Useful in reshaping and flattening arrays.

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # 10
print(arr[-1])  # 50


10
50


In [2]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix[1, 0])  # 3


3


In [3]:
print(arr[arr > 25])  # [30 40 50]


[30 40 50]


In [4]:
arr[2] = 99
print(arr)  # [10 20 99 40 50]


[10 20 99 40 50]


In [5]:
data = np.array([5, 15, 25, 35])
print(data[data > 20])  # [25 35]


[25 35]


In [6]:
data[data > 20] = 99
print(data)  # [ 5 15 99 99]


[ 5 15 99 99]


In [7]:
a = np.array([1, 2, 3])
b = a[a > 1] * 10
print(b)  # [20 30]


[20 30]


In [8]:
mat = np.array([[1, 2], [3, 4], [5, 6]])
print(mat[[0, 2]])  # [[1 2] [5 6]]


[[1 2]
 [5 6]]


In [9]:
print(mat[1, :])  # [3 4]
print(mat[:, 1])  # [2 4 6]


[3 4]
[2 4 6]


In [10]:
a = np.array([1, 2, 3, 4])
mask = a > 2
print(a[mask])  # [3 4]


[3 4]


In [11]:
a[a > 2] = 0
print(a)  # [1 2 0 0]


[1 2 0 0]


In [12]:
print(a[[1, 3]])  # [2 0]


[2 0]


In [13]:
b = np.arange(27).reshape((3, 3, 3))
print(b[1, 1, 1])  # 13


13


In [14]:
print(a[-1])  # 0


0


## Basic Indexing i.e. 1D Arrays.


- Basic indexing accesses individual elements using their position.

- Index starts from 0 in Python (0-based indexing).

- Syntax: array[index]

- You can access the last elements using negative indices.

- Indexing returns the value at that position.

- You can also assign new values using indexing.

- If you index out of bounds, it throws an error.

- Works the same for lists and NumPy arrays.

- Helps retrieve scalar values from arrays.

- Efficient for element-wise access.

- Indexing works with slicing or boolean masks too.

- It’s the simplest and most common way to work with arrays.

In [25]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])
print(a[0])  # 10
print(a[2])  # 30
a[1] = 99
print(a)  # [10 99 30 40 50]
# print(a[10])  # IndexError
for i in range(len(a)):
    print(a[i])


10
30
[10 99 30 40 50]
10
99
30
40
50


## Indexing in 2D Arrays.

- 2D arrays are like tables: rows and columns.

- Access elements using two indices: array[row, column].

- Indexing is zero-based for both axes.

- Negative indexing works for rows/columns.

- You can use indexing to access entire rows/columns.

- Use slicing in combination with indexing.

- Array[row] gives the entire row.

- Array[:, col] gives the entire column.

- Modifying values works the same.

- Indexing a 2D array returns either a value or a 1D array.

- You can loop over rows and access columns with indexing.

- It is widely used in matrix and image operations.

In [26]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[1, 2])  # 6
print(b[0])  # [1 2 3]
print(b[:, 0])  # [1 4 7]
b[2, 1] = 88
print(b)
print(b[-1, -1])  # 9
for row in b:
    print(row)


6
[1 2 3]
[1 4 7]
[[ 1  2  3]
 [ 4  5  6]
 [ 7 88  9]]
9
[1 2 3]
[4 5 6]
[ 7 88  9]


##  Indexing in 3D Arrays.


- 3D arrays have 3 axes: depth, row, column.

- Syntax: array[depth, row, column]

- Useful in working with video, volume data, etc.

- You can access full planes/slices with :.

- Each axis follows zero-based indexing.

- Negative indexing works the same way.

- Indexing returns either values or 2D/1D subarrays.

- It’s common in SciPy for scientific computing.

- Can be combined with slicing and loops.

- Assignment and retrieval both supported.

- Great for handling stacked data like color images.

- Indexing gives fine control over 3D data.

In [27]:
c = np.arange(27).reshape(3, 3, 3)
print(c[0])
print(c[2, 1, 0])  # 21
print(c[:, 1, 1])  # [4 13 22]
c[1, 2, 2] = 999
print(c[1])
for i in range(c.shape[0]):
    print(c[i])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
21
[ 4 13 22]
[[  9  10  11]
 [ 12  13  14]
 [ 15  16 999]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  9  10  11]
 [ 12  13  14]
 [ 15  16 999]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
 Negative Indexing(1D Array).

## Array Slicing in SciPy.

- Array Slicing means accessing a portion of an array (a "slice") using indices, instead of the whole array.

- In SciPy, array slicing is the same as NumPy slicing because SciPy builds on top of NumPy arrays.

- You can slice 1D, 2D, or even multi-dimensional arrays using the slicing syntax start:stop:step.

- Start is the index where slicing begins, stop is where it ends (exclusive), and step defines how many indices to skip.

- You can omit start, stop, or step. For example, arr[::2] will slice every second element from the entire array.

- You can also use negative indices to count from the end of the array, like arr[-1] for the last element.

- For 2D arrays, you use slicing like array[row_start:row_end, col_start:col_end].

- Slicing does not copy data—it creates a view of the original array, meaning changes affect the original.

- You can slice arrays to select specific rows, columns, or blocks from a matrix.

- You can also combine slicing with Boolean indexing or fancy indexing for more control.

- You can reverse an array using slicing with a negative step, e.g. arr[::-1].

- Slicing is useful in data manipulation, matrix operations, subsetting data, and many scientific applications.

- Array slicing means extracting a sub-part of an array (like cutting a piece from it).

- It uses [start:stop:step] syntax.

- It works for 1D, 2D, 3D or higher dimensional arrays.

- Start index is where the slice begins (inclusive).

- Stop index is where it ends (exclusive).

- Step tells how many steps to skip between values.

- If any part is left empty, Python uses default values.

- Slicing does not copy data — it returns a view (linked to original array).

- You can slice rows, columns, or both in 2D arrays.

- You can combine slicing and indexing together.

- You can even reverse arrays using slicing.

- It’s part of NumPy, which SciPy uses for all its array operations.

- Lightweight operation – doesn’t duplicate memory.

- Flexible syntax – you can slice any combination of rows, columns, etc.

- Multi-dimensional slicing is fully supported.

- Works seamlessly with Boolean arrays and fancy indexing.

- Can be used to assign new values to a slice.

- Negative indices allow backwards slicing.

- Easily supports row/column extraction.

- Compatible with SciPy functions (e.g., extract regions before applying transformations).

- Efficient for time series, signals, and matrices.

- Can be used to create reversed arrays, diagonals, or patterns.

- Part of the NumPy foundation, on which SciPy is built.

- SciPy inherits slicing behavior from NumPy arrays.

- You use square brackets and the slice notation.

- In multi-dimensional arrays, each dimension is separated by commas.

- You can slice multiple dimensions at once.

- If you omit a slice, it includes the whole dimension.

- You can use slices in assignments to change subarrays.

- The result of slicing is usually a view (not a new copy).

- Changes to a slice affect the original array (if not a fancy index).

- Supports advanced slicing: mix of slice, index, and conditions.

- Works the same way in SciPy modules (e.g., scipy.ndimage, scipy.signal, etc.).

- Slicing is vectorized, meaning it's fast and efficient.

- Great for manipulating matrices, images, signals, and data tables.



In [15]:
import numpy as np
a = np.arange(10)         # [0 1 2 3 4 5 6 7 8 9]

print(a[2:7])              # Slice from index 2 to 6 => [2 3 4 5 6]
print(a[:5])               # From start to index 4 => [0 1 2 3 4]
print(a[5:])               # From index 5 to end => [5 6 7 8 9]
print(a[::2])              # Every second element => [0 2 4 6 8]
print(a[::-1])             # Reversed array => [9 8 7 6 5 4 3 2 1 0]


[2 3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [16]:
data = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Extract center element
print(data[1:2, 1:2])     # [[50]]

# Get top-left 2x2 corner
print(data[:2, :2])       # [[10 20]
                          #  [40 50]]

# Reverse rows
print(data[::-1, :])      # [[70 80 90]
                          #  [40 50 60]
                          #  [10 20 30]]


[[50]]
[[10 20]
 [40 50]]
[[70 80 90]
 [40 50 60]
 [10 20 30]]


In [17]:
a = np.arange(16).reshape(4, 4)

# 1. Slice entire 2nd row
print(a[1, :])            # [4 5 6 7]

# 2. Slice first column
print(a[:, 0])            # [0 4 8 12]

# 3. Slice center 2x2 block
print(a[1:3, 1:3])        # [[5 6]
                          #  [9 10]]

# 4. Assign new values
a[0:2, 0:2] = 99
print(a)

# 5. Backward slicing of columns
print(a[:, ::-1])         # reverse columns in each row


[4 5 6 7]
[ 0  4  8 12]
[[ 5  6]
 [ 9 10]]
[[99 99  2  3]
 [99 99  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2 99 99]
 [ 7  6 99 99]
 [11 10  9  8]
 [15 14 13 12]]


In [18]:
matrix = np.arange(36).reshape(6, 6)

# 1. Slice rows 2 to 5 and cols 1 to 4
sub = matrix[2:5, 1:4]
print(sub)

# 2. Use slicing to zero out a section
matrix[1:3, 3:5] = 0
print(matrix)

# 3. Reverse slice: last 3 rows
print(matrix[-3:, :])

# 4. Step slice: every 2nd column
print(matrix[:, ::2])

# 5. Slicing for image region (simulate a 2D image)
image = np.random.randint(0, 255, (10, 10))
cropped = image[2:8, 2:8]
print(cropped)


[[13 14 15]
 [19 20 21]
 [25 26 27]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  0  0 11]
 [12 13 14  0  0 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 0  2  4]
 [ 6  8  0]
 [12 14  0]
 [18 20 22]
 [24 26 28]
 [30 32 34]]
[[183 145  11  32 141 167]
 [ 54 182 137 201  94 217]
 [  0 183 254 133 157 215]
 [227 117 124 211  46  35]
 [ 71  19  69 164 223 213]
 [115 139 241 115  54  69]]


## Basic Slicing (1D Arrays).


- Basic Slicing lets you extract a section of a 1D array using [start:stop].

- start is the index where the slice begins.

- stop is the index where the slice ends (not included).

- If start is omitted, slicing begins from the start.

- If stop is omitted, it goes until the end.

- You can think of it like cutting a piece of a list.

- Works for both reading and assigning values.

- Only the section you specify is accessed.

- Keeps memory efficient — creates a view, not a copy.

- Useful in trimming or chunking data.

- Works the same for lists and NumPy arrays.

- Index starts from 0 in Python.



In [21]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60])
print(a[1:4])  # [20 30 40]
print(a[:3])  # [10 20 30]
print(a[2:])  # [30 40 50 60]
print(a[:])  # [10 20 30 40 50 60]
a[1:3] = [99, 88]
print(a)  # [10 99 88 40 50 60]




[20 30 40]
[10 20 30]
[30 40 50 60]
[10 20 30 40 50 60]
[10 99 88 40 50 60]


## Slicing with Step Value.

- The syntax is array[start:stop:step].

- Step defines how many indices to jump.

- A step of 2 selects every second element.

- Step can be positive or negative.

- With step, slicing becomes powerful for spaced data.

- Omitting start or stop still works with step.

- Useful for thinning data or pattern selection.

- Works with multidimensional arrays too.

- Combining step with reverse slicing is common.

- Step cannot be 0; it will raise an error.

- Allows slicing patterns or intervals.

- Reduces the need for loops in certain tasks.

In [22]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(b[::2])  # [1 3 5 7]
print(b[::3])  # [1 4 7]
print(b[1::2])  # [2 4 6 8]
print(b[1:6:2])  # [2 4 6]
print(b[::1])  # [1 2 3 4 5 6 7 8]


[1 3 5 7]
[1 4 7]
[2 4 6 8]
[2 4 6]
[1 2 3 4 5 6 7 8]


## Negative Indexing in Slicing.


- Negative indices count from the end.

-  -1 is the last item, -2 is second last, etc.

- Allows slicing without knowing the length.

- Syntax: array[-start:-stop]

- Useful for trimming or tail slicing.

- You can mix negative and positive indices.

- Often used with step -1 to reverse arrays.

- Cleaner alternative to len(arr) based logic.

- Especially helpful with dynamic data.

- Works on all dimensions.

- Often seen in removing last few items.

- Doesn’t change the array, only views it.

In [23]:
c = np.array([10, 20, 30, 40, 50])
print(c[-1])  # 50
print(c[-2:])  # [40 50]
print(c[1:-1])  # [20 30 40]
print(c[-4:-1])  # [20 30 40]
print(c[::-1])  # [50 40 30 20 10]


50
[40 50]
[20 30 40]
[20 30 40]
[50 40 30 20 10]
