## Array Arithmetic in SciPy.


- In SciPy (via NumPy), array arithmetic means performing operations like addition, subtraction, multiplication, and division directly between arrays, element by element.

- SciPy extends NumPy, and all array arithmetic is done using NumPy arrays (ndarray). These arrays allow efficient, fast computation.

- Element-wise operations require arrays to have the same shape, or compatible shapes via broadcasting.

- Broadcasting automatically expands smaller arrays to match the shape of larger ones, if compatible.

- Operations are applied to all elements without explicit for-loops, making the code cleaner and faster.

- Array arithmetic works on 2D, 3D, or higher-dimensional arrays, supporting matrix and tensor operations.

- You can apply scalar values (like 2) to an array. It will apply the operation to every element.

- NumPy and SciPy support universal functions (ufuncs) like np.sin(), np.exp(), etc., which operate element-wise.

- Use np.dot() or @ operator for matrix multiplication, not element-wise.

- You can compare arrays element-wise (>, <, ==) and apply logical operators like &, |, ~.

- You can calculate sum, mean, min, max across an entire array or along a specific axis.

- Use .T to transpose and .reshape() to change the shape of an array to make it suitable for arithmetic.



In [2]:
#1) Array Arithmetic refers to Element-wise Operations on Arrays.

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]


[5 7 9]
[ 4 10 18]


In [3]:
#2) SciPy uses NumPy Arrays for Array Arithmetic.

from scipy import linalg
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(type(a))  # <class 'numpy.ndarray'>


<class 'numpy.ndarray'>


In [4]:
#3) Operations Work on Arrays of the Same Shape.

a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])

print(a + b)  # [[11 22] [33 44]]


[[11 22]
 [33 44]]


In [6]:
#4) Broadcasting Enables Operations on Different Shapes.

a = np.array([[1], [2], [3]])  # Shape: (3,1)
b = np.array([10, 20, 30])     # Shape: (3,)

# Broadcasting to (3,3).
print(a + b)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [7]:
#5) Array Arithmetic is Vectorized(No Loops Needed).

a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 2, 2])

# Instead of: [a[i] * b[i] for i in range(len(a))]
print(a * b)  # [2 4 6 8]


[2 4 6 8]


In [8]:
#6) Works with Multi-Dimensional Arrays.

a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])

print(a * b)  # [[2 0] [3 8]]


[[2 0]
 [3 8]]


In [9]:
#7) Supports Scalar Operations with Arrays.

a = np.array([1, 2, 3])
print(a * 2)  # [2 4 6]
print(a + 5)  # [6 7 8]


[2 4 6]
[6 7 8]


In [10]:
#8)  Supports Mathematical Functions(ufuncs).


x = np.array([0, np.pi/2, np.pi])
print(np.sin(x))  # [0. 1. 0.]


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [11]:
#9) Matrix Multiplication(Dot Product).

a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])

print(np.dot(a, b))  # Matrix product
# OR
print(a @ b)


[[ 4  4]
 [10  8]]
[[ 4  4]
 [10  8]]


In [12]:
#10) Supports Logical Operations on Arrays.

a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

print(a > b)        # [False False  True]
print((a > 1) & (a < 3))  # [False  True False]


[False False  True]
[False  True False]


In [13]:
#11)  Aggregation Functions Work on Arrays.


a = np.array([[1, 2], [3, 4]])

print(np.sum(a))         # 10
print(np.mean(a, axis=0)) # [2. 3.]


10
[2. 3.]


In [14]:
#12)  Transpose and Reshape Help in Aligning Arrays.

a = np.array([[1, 2], [3, 4]])
print(a.T)  # [[1 3] [2 4]]

b = np.array([1, 2, 3, 4])
print(b.reshape((2, 2)))  # [[1 2] [3 4]]


[[1 3]
 [2 4]]
[[1 2]
 [3 4]]


## Enables High-Performance Scientific Computation.

- Array Arithmetic in SciPy enables fast, vectorized numerical operations—much faster than Python loops—which is essential for scientific computing.

In [16]:
import numpy as np

a = np.arange(1_000_000)
b = np.arange(1_000_000)

result = a + b  # Fast, vectorized addition.
print(result)


[      0       2       4 ... 1999994 1999996 1999998]


## Eliminates Need for Manual Loops.

- Array operations are applied to all elements at once, removing the need for for loops. This makes code shorter and easier to read.

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Without loop
print(a + b)  # [5 7 9]


[5 7 9]


## Supports Operations on Multi-Dimensional Data.


- Many scientific problems involve matrices or 3D/4D arrays (like images or time series). Array arithmetic supports multi-dimensional operations directly.

In [18]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])

print(a + b)  # Element-wise addition on 2D arrays


[[11 22]
 [33 44]]


## Supports Broadcasting for Flexible Operations.

- With broadcasting, you can operate on arrays of different shapes. This is extremely useful for processing batch data, matrices, or applying constants.

In [19]:
a = np.array([[1, 2, 3]])
b = np.array([[1], [2], [3]])

print(a + b)  # (3x1) + (1x3) → (3x3)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


## Enables Mathematical Modeling and Simulation.

- Array arithmetic is used to simulate systems—physical, biological, financial—by applying formulas across large datasets.

In [20]:
# Modeling exponential growth
population = np.array([100, 200, 300])
growth_rate = 1.05

future_population = population * growth_rate
print(future_population)


[105. 210. 315.]


## Allows Efficient Aggregation and Statistics.

- Using array operations, we can easily compute statistics like sum, mean, std across dimensions, which is common in scientific data.

In [21]:
data = np.array([[1, 2], [3, 4]])

print(np.mean(data))        # Mean of all elements
print(np.sum(data, axis=0)) # Column-wise sum


2.5
[4 6]


## Element-wise Arithmetic Operations.

- Basic arithmetic operations like +, -, *, / are applied element-wise if arrays have the same shape or are broadcast-compatible.

In [22]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]


[5 7 9]
[ 4 10 18]


## Using Universal Functions(UFuncs).


- SciPy/NumPy use ufuncs like np.add(), np.subtract(), np.multiply(), np.divide() as vectorized implementations of operations.
     

In [23]:
print(np.add(a, b))       # [5 7 9]
print(np.multiply(a, b))  # [4 10 18]


[5 7 9]
[ 4 10 18]


##  Scalar and Array Arithmetic.


- Operations between arrays and scalars apply the operation to each element (broadcasting a scalar to the array).

In [24]:
print(a + 10)  # [11 12 13]
print(a * 2)   # [2 4 6]


[11 12 13]
[2 4 6]


##  Matrix Multiplication vs. Element-wise Multiplication.


- Use @ or np.matmul() for matrix multiplication, not *, which performs element-wise multiplication.

In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A * B)       # Element-wise
print(A @ B)       # Matrix multiplication


[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


## Broadcasting Mechanism.


- Broadcasting allows operations on arrays of different shapes by virtually expanding one of them without copying data.

In [26]:
a = np.array([[1], [2], [3]])  # Shape: (3,1)
b = np.array([10, 20])         # Shape: (2,)

print(a + b)  # Broadcasted to (3,2)


[[11 21]
 [12 22]
 [13 23]]


## Arithmetic on Multidimensional Arrays.


- Array Arithmetic is not limited to 1D or 2D. It can work on 3D, 4D, etc., as long as shapes are compatible.

In [27]:
c = np.ones((2, 3, 4))
d = np.full((2, 3, 4), 5)

print(c + d)  # Add 1 to each 5 → all 6s


[[[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]

 [[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]]


## Arithmetic with Boolean Arrays.


- Boolean Arrays(e.g., from comparisons) can be used for masking, conditionally modifying elements.

In [28]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3

print(arr[mask])      # [4 5]
print(arr * mask)     # [0 0 0 4 5]


[4 5]
[0 0 0 4 5]


## Conditional Array Arithmetic using np.where().

- Use np.where(condition, x, y) to return values from x or y based on the condition, applied element-wise.

In [29]:
a = np.array([1, 2, 3, 4, 5])
b = np.where(a % 2 == 0, a * 10, a)
print(b)  # [1 20 3 40 5]


[ 1 20  3 40  5]


## Aggregation Operations (Sum, Mean, etc.).

- You can use array arithmetic followed by aggregation like np.sum(), np.mean() to summarize data.

In [30]:
x = np.array([[1, 2], [3, 4]])

print(np.sum(x))         # 10
print(np.mean(x, axis=0))  # [2. 3.]


10
[2. 3.]


## Reshape and Transpose for Compatibility.

- Use .reshape() or .T (transpose) to change array shapes to make them compatible for arithmetic operations.

In [31]:
x = np.array([1, 2, 3, 4])
y = x.reshape((2, 2))

print(y)
print(y.T)  # Transpose


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


## Type Conversion for Safe Arithmetic.


- Ensure type compatibility using .astype(), especially when working with mixed integers, floats, or complex numbers.

In [32]:
a = np.array([1, 2, 3])
b = np.array([0.1, 0.2, 0.3])

result = a + b  # Implicit upcasting to float
print(result)


[1.1 2.2 3.3]


##  Arithmetic with scipy.sparse Arrays.


- For memory-efficient large matrix arithmetic, use scipy.sparse arrays. They support limited element-wise and matrix operations.

In [33]:
from scipy.sparse import csr_matrix

a = csr_matrix([[1, 0], [0, 2]])
b = csr_matrix([[0, 3], [4, 0]])

c = a + b
print(c.toarray())  # [[1 3], [4 2]]


[[1 3]
 [4 2]]
