## Sparse Matrices in SciPy.


- A Sparse Matrix is a Matrix that contains mostly zero elements. Typically, if more than 50% of its elements are zero, it's considered sparse.

- In a dense matrix, most elements are non-zero. Sparse matrices reduce memory usage compared to dense matrices.

- They save memory and computational resources by storing only non-zero elements, which is crucial for large-scale data.

- Sparse matrices are used in NLP (text), recommender systems, computer graphics, scientific computing, etc.

- You can add, subtract, and multiply sparse matrices just like dense matrices, but much faster and using less memory.

- You can access individual rows, columns, or elements efficiently using sparse matrix formats like CSR.

- You can convert a sparse matrix to a dense matrix using .toarray() or .todense(), and vice versa.

- Sparse identity, diagonal, or random matrices are useful in simulations and ML models.

- Sparse matrices are used in solving large systems of linear equations (Ax = b) efficiently.

  

In [1]:
#1) Definition of Sparse Matrix.

import numpy as np

dense_matrix = np.array([
    [0, 0, 3],
    [0, 0, 0],
    [4, 0, 0]
])
print("Dense matrix:\n", dense_matrix)


Dense matrix:
 [[0 0 3]
 [0 0 0]
 [4 0 0]]


In [2]:
#2) Contrast with Dense Matrix.

from scipy.sparse import csr_matrix

sparse_matrix = csr_matrix(dense_matrix)
print("Sparse matrix (CSR format):\n", sparse_matrix)


Sparse matrix (CSR format):
 <Compressed Sparse Row sparse matrix of dtype 'int32'
	with 2 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	3
  (2, 0)	4


In [3]:
#3) Sparse Matrices save memory.

from sys import getsizeof

print("Size of dense:", getsizeof(dense_matrix))
print("Size of sparse:", getsizeof(sparse_matrix))  # Smaller


Size of dense: 164
Size of sparse: 48


In [4]:
#4) Common Real-world Examples.

from sklearn.feature_extraction.text import CountVectorizer

texts = ["data science", "machine learning", "science and AI"]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)

print("Sparse text matrix:\n", X)
print("Dense form:\n", X.toarray())


Sparse text matrix:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 7 stored elements and shape (3, 6)>
  Coords	Values
  (0, 2)	1
  (0, 5)	1
  (1, 4)	1
  (1, 3)	1
  (2, 5)	1
  (2, 1)	1
  (2, 0)	1
Dense form:
 [[0 0 1 0 0 1]
 [0 0 0 1 1 0]
 [1 1 0 0 0 1]]


In [5]:
#5) Sparse Matrix Arithmetic.

A = csr_matrix([[0, 0, 2], [3, 0, 0]])
B = csr_matrix([[0, 0, 5], [1, 0, 0]])

print("A + B =\n", (A + B).toarray())


A + B =
 [[0 0 7]
 [4 0 0]]


In [6]:
#6) Indexing and Slicing.

print("Row 0 of A:", A.getrow(0).toarray())
print("Column 2 of A:", A.getcol(2).toarray())


Row 0 of A: [[0 0 2]]
Column 2 of A: [[2]
 [0]]


In [7]:
#7) Conversion Between Sparse and Dense.

dense_again = sparse_matrix.toarray()
print("Converted to dense:\n", dense_again)


Converted to dense:
 [[0 0 3]
 [0 0 0]
 [4 0 0]]


In [8]:
#8) Creation of Special Sparse Matrices.

from scipy.sparse import identity, diags

I = identity(4)
D = diags([1, 2, 3, 4])

print("Sparse Identity:\n", I.toarray())
print("Sparse Diagonal:\n", D.toarray())


Sparse Identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Sparse Diagonal:
 [[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


In [9]:
#9) Use in Solving Equations.

from scipy.sparse.linalg import spsolve

A = csr_matrix([[3, 0], [0, 4]])
b = np.array([9, 16])

x = spsolve(A, b)
print("Solution x:", x)


Solution x: [3. 4.]


## Features of Sparse Matrices.

## Memory Efficiency. 

- Sparse Matrices only store non-zero values, which saves significant memory, especially for large matrices.

In [10]:
import numpy as np
from scipy.sparse import csr_matrix
from sys import getsizeof

dense = np.zeros((1000, 1000))
sparse = csr_matrix(dense)

print("Dense size:", getsizeof(dense))        # ~8MB
print("Sparse size:", getsizeof(sparse))      # much smaller


Dense size: 8000128
Sparse size: 48


## Fast Arithmetic Operations.


- Operations like matrix multiplication are optimized in sparse formats.

In [11]:
A = csr_matrix([[0, 0, 1], [0, 2, 0], [3, 0, 0]])
B = csr_matrix([[1, 0, 0], [0, 0, 0], [0, 0, 4]])

result = A @ B
print("Matrix Product:\n", result.toarray())


Matrix Product:
 [[0 0 4]
 [0 0 0]
 [3 0 0]]


## Reduced Storage Complexity.

- Instead of storing all matrix elements, sparse formats store only non-zero values and their indices.

In [12]:
coo = A.tocoo()
print("Data:", coo.data)
print("Row indices:", coo.row)
print("Col indices:", coo.col)


Data: [1 2 3]
Row indices: [0 1 2]
Col indices: [2 1 0]


## Integration with Machine Learning Libraries.

- ML tools like scikit-learn support sparse matrices for feature vectors, TF-IDF, etc.

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

texts = ["hello world", "hello machine learning"]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)

print("Sparse representation (TF matrix):\n", X)
print("Dense form:\n", X.toarray())


Sparse representation (TF matrix):
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5 stored elements and shape (2, 4)>
  Coords	Values
  (0, 0)	1
  (0, 3)	1
  (1, 0)	1
  (1, 2)	1
  (1, 1)	1
Dense form:
 [[1 0 0 1]
 [1 1 1 0]]


## Sparse Identity and Diagonal Matrices.

- Sparse identity or diagonal matrices are common in numerical computations.

In [14]:
from scipy.sparse import identity, diags

I = identity(4)
D = diags([1, 2, 3, 4])

print("Sparse Identity:\n", I.toarray())
print("Sparse Diagonal:\n", D.toarray())


Sparse Identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Sparse Diagonal:
 [[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


## Matrix Transposition Support.


- Transposing a Sparse Matrix doesn't require reshuffling all data; it's done efficiently.

In [16]:
print("Original Matrix:\n", A.toarray())
print("Transposed:\n", A.transpose().toarray())


Original Matrix:
 [[0 0 1]
 [0 2 0]
 [3 0 0]]
Transposed:
 [[0 0 3]
 [0 2 0]
 [1 0 0]]


## Compatibility with Numpy & Scipy Functions.


- Sparse matrices can work with certain numpy/scipy functions (like norms, solving linear systems).

In [17]:
from scipy.sparse.linalg import norm

print("Norm of sparse matrix A:", norm(A))


Norm of sparse matrix A: 3.7416573867739413


## Sparse Identity Matrix.


- A Sparse Identity Matrix is an efficient way to store the identity matrix without using a lot of memory, especially when the size is large.

- Diagonal Elements are all 1 in Sparse Identity Matrix.

- All Off-Diagonal Elements are Zero  :  No values exist outside the diagonal; all other entries are 0.

- Efficient Matrix Multiplication :  Multiplying any matrix with the identity returns the same matrix.





In [32]:
#1) Example 1 : Create a 3x3 Sparse Identity Matrix.

from scipy.sparse import identity
I = identity(3)
print(I.toarray())


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
#2) Diagonal Elements are all 1.

from scipy.sparse import identity

I = identity(4)
print(I.toarray())


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
#4) Efficient Matrix Multiplication.

from scipy.sparse import csr_matrix

A = csr_matrix([[2, 4], [6, 8]])
I = identity(2, format='csr')

print((A @ I).toarray())


[[2. 4.]
 [6. 8.]]


## Examples of Sparse Identity Matrix.

In [36]:
#1) Example 1 : Create a 3x3 Sparse Identity Matrix.

from scipy.sparse import identity

I = identity(3)
print(I.toarray())


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
#2) Example  2 : Create a 5x5 Identity Matrix in CSR Format.

I_csr = identity(5, format='csr')
print(I_csr)


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5 stored elements and shape (5, 5)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0


In [38]:
#3) Example 3 : Create and Print as Dense Array.

I = identity(4)
dense = I.toarray()
print(dense)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [39]:
#4) Example 4 : Multiply Identity with Another Matrix.

from scipy.sparse import csr_matrix

A = csr_matrix([[2, 3], [4, 5]])
I = identity(2, format='csr')
result = A @ I
print(result.toarray())  # Same as A


[[2. 3.]
 [4. 5.]]


In [40]:
#5) Check Number of Non-Zero Elements.

I = identity(1000)
print("Non-zero elements:", I.nnz)



Non-zero elements: 1000


In [41]:
#6) Example 6 : Convert Identity Matrix to CSC Format.

I = identity(3)
I_csc = I.tocsc()
print(type(I_csc))


<class 'scipy.sparse._csc.csc_matrix'>


In [42]:
#7) Example 7 : Use Identity in Addition(A + I).

from scipy.sparse import csr_matrix

A = csr_matrix([[1, 2], [3, 4]])
I = identity(2, format='csr')
sum_matrix = A + I
print(sum_matrix.toarray())


[[2. 2.]
 [3. 5.]]


In [43]:
#8) Example 8 : Scale Identity Matrix.

from scipy.sparse import diags

scaled_I = diags([10, 10, 10])  # 10 * Identity
print(scaled_I.toarray())


[[10.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 10.]]


In [44]:
#9) Example 9 : Use Identity as Mask(Keep Only Diagonal).

from scipy.sparse import csr_matrix

A = csr_matrix([[5, 6], [7, 8]])
I = identity(2)
masked = A.multiply(I)  # Keeps only diagonal
print(masked.toarray())


[[5. 0.]
 [0. 8.]]


In [45]:
#10) Example 10 : arge Identity Matrix Creation and Shape Check.

large_I = identity(100000, format='csr')
print("Shape:", large_I.shape)
print("Stored non-zeros:", large_I.nnz)


Shape: (100000, 100000)
Stored non-zeros: 100000


## Sparse Diagonal Matrix.

- A Sparse Diagonal Matrix is a square matrix where only the diagonal (or a few diagonals) contains non-zero values. All other elements are zero. It's useful when you want to save space and compute faster.

- Only Diagonal Values are Non - Zero  : Only the values on the diagonal line (top-left to bottom-right) are non-zero; the rest are all zeros.

- Saves Memory Compared to Full Matrix  :  Sparse storage saves memory by not storing the zero values.

- Supports Multiple Diagonals :  You can combine several diagonals (e.g., main, upper, lower).

- Fast for Matrix Operations  : Diagonal Matrices multiply and invert quickly compared to full Matrices.

- Diagonal Extraction and Manipulation :  You can extract or modify the diagonal easily.

- Fast Element-wise Multiplication  :  You can apply them like filters or masks to keep or scale only diagonal elements.

In [46]:
#1) Basic Diagonal Matrix.

D = diags([1, 2, 3])
print(D.toarray())


[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [47]:
#2) Only Diagonal Values are Non-Zero.

from scipy.sparse import diags

D = diags([1, 2, 3])
print(D.toarray())


[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [48]:
#3) Saves Memory Compared to Full Matrix.

large_diag = diags([1]*1000000)
print("Non-zero elements:", large_diag.nnz)


Non-zero elements: 1000000


In [49]:
#4) Supports Multiple Diagonals.

multi_diag = diags([[1, 2, 3], [4, 5]], offsets=[0, 1])
print(multi_diag.toarray())


[[1. 4. 0.]
 [0. 2. 5.]
 [0. 0. 3.]]


In [50]:
#5) Fast Element-Wise Multiplication.

A = csr_matrix([[2, 4], [5, 7]])
D = diags([1, 0])  # Keep row 0, remove row 1
print((D @ A).toarray())




[[2. 4.]
 [0. 0.]]


## Examples of Sparse Diagonal Matrix.

In [51]:
#1)  Example 1  :  Diagonal Matrix with Constant Value.

D = diags([5]*4)
print(D.toarray())


[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


In [52]:
#2) Example 2  : Two Diagonals: Main and Upper.

D = diags([[10, 20, 30], [1, 1]], offsets=[0, 1])
print(D.toarray())


[[10.  1.  0.]
 [ 0. 20.  1.]
 [ 0.  0. 30.]]


In [53]:
#3) Example 3  :  Two Diagonals: Main and Lower.

D = diags([[5, 5, 5], [7, 8]], offsets=[0, -1])
print(D.toarray())


[[5. 0. 0.]
 [7. 5. 0.]
 [0. 8. 5.]]


In [54]:
#4) Example 4 : Identity Matrix via diags.

D = diags([1, 1, 1])
print(D.toarray())


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
#5) Example 5  :  Create Sparse Matrix with Zeros on Diagonal.

D = diags([0, 0, 0])
print(D.toarray())


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [57]:
#6) Example 6 :  Negative Values on Diagonal.

D = diags([-1, -2, -3])
print(D.toarray())


[[-1.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  0. -3.]]


## Indexing and Slicing.

- Access specific rows, columns, and elements efficiently using sparse formats (mainly CSR).

In [18]:
print("Row 1:", A.getrow(1).toarray())
print("Column 0:", A.getcol(0).toarray())


Row 1: [[0 2 0]]
Column 0: [[0]
 [0]
 [3]]


## Applying Sparse Matrices in Machine Learning.


- Sparse matrices are critical for handling high-dimensional input like: One-hot encoding, TF-IDF and Bag-of-words etc.

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

docs = ["AI is great", "AI and ML", "ML is evolving"]
vec = TfidfVectorizer()
X = vec.fit_transform(docs)

print("TF-IDF Matrix (sparse):", X)
print("Dense form:\n", X.toarray())


TF-IDF Matrix (sparse): <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9 stored elements and shape (3, 6)>
  Coords	Values
  (0, 0)	0.5178561161676974
  (0, 4)	0.5178561161676974
  (0, 3)	0.680918560398684
  (1, 0)	0.5178561161676974
  (1, 1)	0.680918560398684
  (1, 5)	0.5178561161676974
  (2, 4)	0.5178561161676974
  (2, 5)	0.5178561161676974
  (2, 2)	0.680918560398684
Dense form:
 [[0.51785612 0.         0.         0.68091856 0.51785612 0.        ]
 [0.51785612 0.68091856 0.         0.         0.         0.51785612]
 [0.         0.         0.68091856 0.         0.51785612 0.51785612]]


## Matrix Operations(Add, Multiply and Transpose).

- Master Operations like addition, multiplication, and transposition directly on sparse matrices.

In [20]:
A = csr_matrix([[0, 2], [3, 0]])
B = csr_matrix([[1, 0], [0, 4]])

print("Addition:\n", (A + B).toarray())
print("Multiplication:\n", (A @ B).toarray())
print("Transpose:\n", A.transpose().toarray())


Addition:
 [[1 2]
 [3 4]]
Multiplication:
 [[0 8]
 [3 0]]
Transpose:
 [[0 3]
 [2 0]]


## Solving Sparse Linear Systems.

- Learn to solve Ax = b when A is sparse using optimized solvers like spsolve.

In [21]:
from scipy.sparse.linalg import spsolve

A = csr_matrix([[3, 0], [0, 4]])
b = np.array([9, 8])
x = spsolve(A, b)

print("Solution x:", x)


Solution x: [3. 2.]


## Types of Sparse Matrix Representations.

- The different types of Sparse Matrix are  : COO(Coordinate Format),  CSR(Compressed Sparse Row) and CSC(Compressed Sparse Column)

## COO(Coordinate Format) 

- COO stands for Coordinate Format. It stores the matrix by keeping three arrays:

-  data: values of non-zero elements i.e. this List stores all the non-zero numbers in the matrix.  Example: If your matrix has the numbers 5, 8, and 3 that are not zero, then:
- data = [5, 8, 3]

- row: row Index of each Non-Zero Value i.e. this list tells us which row each value from the data list is in.  Example: If those numbers appear in row 0, row 1, and row 2:
- row = [0, 1, 2]
   
- col: column index of each Non-Zero Value i.e. this List tells us which Column each value from the data list is in.
- col = [2, 0, 1]





- It work together :  data = [5, 8, 3],  row = [0, 1, 2] and col = [2, 0, 1] i.e. This means:
- Put 5 at position (0, 2).
- Put 8 at position (1, 0).
- Put 3 at position (2, 1).
- All the other places in the matrix are assumed to be 0.
    






## Examples of COO.

In [4]:
#1) Example 1 : Simple Example of COO.


from scipy.sparse import coo_matrix
import numpy as np

data = np.array([5, 8, 3])
rows = np.array([0, 1, 2])
cols = np.array([2, 0, 1])

coo = coo_matrix((data, (rows, cols)), shape=(3, 3))

print("COO Matrix:\n", coo.toarray())
print("Data:", coo.data)
print("Row indices:", coo.row)
print("Column indices:", coo.col)


COO Matrix:
 [[0 0 5]
 [8 0 0]
 [0 3 0]]
Data: [5 8 3]
Row indices: [0 1 2]
Column indices: [2 0 1]


In [5]:
#2) Example 2 : One Non-Zero Element.

data = [10]
row = [0]
col = [1]

matrix = coo_matrix((data, (row, col)), shape=(2, 2))
print(matrix.toarray())


[[ 0 10]
 [ 0  0]]


In [6]:
#3) Example 3 : Diagonal Elements.


data = [1, 2, 3]
row = [0, 1, 2]
col = [0, 1, 2]

matrix = coo_matrix((data, (row, col)), shape=(3, 3))
print(matrix.toarray())


[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [7]:
#4) Example 4 : Upper Triangle Only.

data = [5, 7, 9]
row = [0, 0, 1]
col = [1, 2, 2]

matrix = coo_matrix((data, (row, col)), shape=(3, 3))
print(matrix.toarray())


[[0 5 7]
 [0 0 9]
 [0 0 0]]


In [8]:
#5) Example 5  : Lower Triangle Only.


data = [2, 4, 6]
row = [1, 2, 2]
col = [0, 0, 1]

matrix = coo_matrix((data, (row, col)), shape=(3, 3))
print(matrix.toarray())


[[0 0 0]
 [2 0 0]
 [4 6 0]]


In [9]:
#6) Example 6 : Full First Row.

data = [3, 4, 5]
row = [0, 0, 0]
col = [0, 1, 2]

matrix = coo_matrix((data, (row, col)), shape=(3, 3))
print(matrix.toarray())


[[3 4 5]
 [0 0 0]
 [0 0 0]]


In [10]:
#7) Example 7 : Random 3×4 Matrix.

data = [9, 1, 2]
row = [0, 2, 1]
col = [3, 2, 0]

matrix = coo_matrix((data, (row, col)), shape=(3, 4))
print(matrix.toarray())


[[0 0 0 9]
 [2 0 0 0]
 [0 0 1 0]]


In [13]:
# Example 8 : 2×2 Matrix with All Non-Zeros.

data = [1, 2, 3, 4]
row = [0, 0, 1, 1]
col = [0, 1, 0, 1]

matrix = coo_matrix((data, (row, col)), shape=(2, 2))
print(matrix.toarray())


[[1 2]
 [3 4]]


In [14]:
# Example 9  :  Empty Matrix(No Non-Zeros).

data = []
row = []
col = []

matrix = coo_matrix((data, (row, col)), shape=(3, 3))
print(matrix.toarray())


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Features of COO(Coordinate Format) Matrix.


## Stores Only Non-Zero Elements : COO only keeps track of the non-zero elements, saving space.

In [15]:
from scipy.sparse import coo_matrix

data = [4, 7]
row = [0, 1]
col = [2, 0]

matrix = coo_matrix((data, (row, col)), shape=(3, 3))
print(matrix.toarray())


[[0 0 4]
 [7 0 0]
 [0 0 0]]


## Simple Structure Using 3 Arrays. : It uses three arrays: data, row, and col.

In [16]:
print("Values :", matrix.data)
print("Rows   :", matrix.row)
print("Cols   :", matrix.col)


Values : [4 7]
Rows   : [0 1]
Cols   : [2 0]


## Easy to Build Manually : You can build COO matrices from scratch by specifying values and their positions.

In [17]:
data = [1, 2, 3]
row = [0, 1, 2]
col = [1, 2, 0]

matrix = coo_matrix((data, (row, col)), shape=(3, 3))
print(matrix.toarray())


[[0 1 0]
 [0 0 2]
 [3 0 0]]


## Supports Duplicate Entries(Auto Sums) : If you insert multiple values at the same position, COO adds them up.

In [18]:
data = [5, 7]
row = [1, 1]
col = [0, 0]

matrix = coo_matrix((data, (row, col)), shape=(2, 2))
print(matrix.toarray())


[[ 0  0]
 [12  0]]


## Fast to Construct(Good for Dynamic Insertions) : You can easily append new entries during runtime.

In [19]:
data = [1]
row = [0]
col = [0]

# Adding more data
data += [2, 3]
row += [1, 2]
col += [1, 2]

matrix = coo_matrix((data, (row, col)), shape=(3, 3))
print(matrix.toarray())


[[1 0 0]
 [0 2 0]
 [0 0 3]]


## Order of Data Doesn't Matter :  COO accepts entries in any order — no sorting needed.

In [20]:
data = [2, 9, 5]
row = [2, 0, 1]
col = [0, 2, 1]

matrix = coo_matrix((data, (row, col)), shape=(3, 3))
print(matrix.toarray())


[[0 0 9]
 [0 5 0]
 [2 0 0]]


## Easy to Visualize : You can easily view and debug COO format using .toarray() or .data, .row, .col.

In [21]:
print("Full matrix:\n", matrix.toarray())


Full matrix:
 [[0 0 9]
 [0 5 0]
 [2 0 0]]


## Easy Conversion to Other Formats(CSR, CSC)  : You can convert COO to faster formats for computation.

In [22]:
csr = matrix.tocsr()
print("CSR format:\n", csr.toarray())


CSR format:
 [[0 0 9]
 [0 5 0]
 [2 0 0]]


## CSR – Compressed Sparse Row.

- CSR stores the matrix by Compressing the Rows. It uses Three Arrays : 
    
- data: Non - Zero Values i.e. this Array holds only the values that are not Zero i.e. For Example, if your matrix is  :
- [ 5 0 0 ]

  
  [ 0 0 8 ]

  
  [ 0 3 0 ]


- Then, the non-zero values are : data = [5, 8, 3].


- indices – The column index of each non-zero value i.e. this tells us where each value is in its Row — specifically, the Column Number.
- In our example:
- 5 is in column 0.
- 8 is in column 2.
- 3 is in column 1.

- So, the indices = [0, 2, 1].



- indptr – Index pointer: where each row starts in data i.e. This array tells us: where each row starts and ends in the data Array. It helps us split the non-zero values back into their original rows. In the example:
- Row 0: 1 non-zero value → starts at index 0, ends before index 1.
- Row 1: 1 value → starts at 1, ends before 2.
- Row 2: 1 value → starts at 2, ends before 3.
- So : indptr = [0, 1, 2, 3] (There is always 1 more element than the number of rows).
    
    
    
 

## Examples of CSR.

In [2]:
#1) Example 1 : Basic Example of CSR. 

from scipy.sparse import csr_matrix

dense_matrix = [
    [5, 0, 0],
    [0, 0, 8],
    [0, 3, 0]
]

csr = csr_matrix(dense_matrix)

print("data   :", csr.data)
print("indices:", csr.indices)
print("indptr :", csr.indptr)
print("Full Matrix:\n", csr.toarray())


data   : [5 8 3]
indices: [0 2 1]
indptr : [0 1 2 3]
Full Matrix:
 [[5 0 0]
 [0 0 8]
 [0 3 0]]


In [3]:
#2) Example 2 : Create from Dense Matrix.


import numpy as np
dense = np.array([[1, 0, 0], [0, 0, 2], [0, 3, 0]])
csr = csr_matrix(dense)
print(csr.toarray())


[[1 0 0]
 [0 0 2]
 [0 3 0]]


In [4]:
#3) Example 3 : Create from Data, Indices, Indptr.

data = [4, 5]
indices = [0, 2]
indptr = [0, 1, 2]

csr = csr_matrix((data, indices, indptr), shape=(2, 3))
print(csr.toarray())


[[4 0 0]
 [0 0 5]]


In [5]:
#4) Example 4 : Zero Matrix.

csr = csr_matrix((3, 3))
print(csr.toarray())



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#5) Example 5 : Single Non-Zero Element.

data = [9]
indices = [1]
indptr = [0, 1]

csr = csr_matrix((data, indices, indptr), shape=(1, 3))
print(csr.toarray())



[[0 9 0]]


In [7]:
#6) Example 6 : Matrix Multiplication with Vector.

csr = csr_matrix([[1, 0, 2], [0, 3, 0]])
vector = np.array([1, 2, 3])

result = csr.dot(vector)
print(result)


[7 6]


In [8]:
#7) Example 7 : Row Access.

csr = csr_matrix([[10, 0, 20], [0, 5, 0]])
print("Row 0:", csr[0].toarray())
print("Row 1:", csr[1].toarray())


Row 0: [[10  0 20]]
Row 1: [[0 5 0]]


In [9]:
#8) Example 8 :  Scalar Multiplication.

csr = csr_matrix([[1, 2], [3, 0]])
print((csr * 2).toarray())



[[2 4]
 [6 0]]


In [10]:
#9) Example 9 :  Sum of All Elements.

csr = csr_matrix([[1, 0, 2], [0, 3, 0]])
print("Sum =", csr.sum())




Sum = 6


## Features of CSR(Compressed Sparse Row) Format Matrix.

## Stores Only Non-Zero Elements Efficiently :  Like COO, CSR only stores Non - Zero Values.

In [11]:
data = [4, 5]
indices = [0, 2]  # column indices
indptr = [0, 1, 2]  # row pointers: row 0 has 1 value, row 1 has 1 value

matrix = csr_matrix((data, indices, indptr), shape=(2, 3))
print(matrix.toarray())


[[4 0 0]
 [0 0 5]]


## Uses Three Arrays: data, indices, indptr i.e. data: non-zero values, indices: column indices of each value and indptr: row index boundaries (starting point of each row)

In [12]:
print("Data   :", matrix.data)
print("Indices:", matrix.indices)
print("IndPtr :", matrix.indptr)


Data   : [4 5]
Indices: [0 2]
IndPtr : [0 1 2]


## Fast for Row Access & Slicing  :  CSR is optimized for row-wise slicing.

In [13]:
print("Row 0:", matrix[0].toarray())
print("Row 1:", matrix[1].toarray())


Row 0: [[4 0 0]]
Row 1: [[0 0 5]]


## Efficient for Matrix-Vector Multiplication.

In [14]:
vec = np.array([1, 2, 3])
result = matrix.dot(vec)
print("Matrix * Vector =", result)


Matrix * Vector = [ 4 15]


## Easier Arithmetic than COO  :   Supports fast Addition, Multiplication, etc.

In [15]:
a = csr_matrix([[1, 0, 2], [0, 3, 0]])
b = csr_matrix([[0, 0, 1], [0, 3, 0]])
sum_matrix = a + b
print(sum_matrix.toarray())


[[1 0 3]
 [0 6 0]]


## Can Be Converted from Other Formats.

In [16]:
from scipy.sparse import coo_matrix

coo = coo_matrix(([1, 2, 3], ([0, 1, 2], [0, 2, 1])), shape=(3, 3))
csr = coo.tocsr()
print("CSR matrix:\n", csr.toarray())


CSR matrix:
 [[1 0 0]
 [0 0 2]
 [0 3 0]]


## Supports Broadcasting and Dense Ops  :  Can perform operations with NumPy Arrays.

In [17]:
dense = np.array([[1, 2, 3], [4, 5, 6]])
csr = csr_matrix(dense)
print((csr * 2).toarray())  # Scalar multiplication


[[ 2  4  6]
 [ 8 10 12]]


## CSC – Compressed Sparse Column.

- CSC stands for Compressed Sparse Column, which is a special way of storing a sparse matrix — a matrix that has lots of zero values.

- Instead of saving Every Number in the Matrix(including zeros), we only save the important non-zero values and where they are — but in a column-wise manner.

- CSC stores the matrix by compressing the columns. It uses :
  
- data: Non - Zero Values i.e. This is just a list of all the non-zero values in the Matrix and we go Column by Column, from left to right, and collect the non-zero values.
- If the matrix is  :

[0 4 0]

  
[1 0 0]

  
[0 2 3]

  
- Then  :  Column  0  has  :  1, Column 1 has: 4, 2 and Column 2 has :  3 and So, the data = [1, 4, 2, 3].
  
 
- indices: Row Indices of each value i.e. Then  :  Column 0 has: 1,  Column 1 has: 4, 2 and  Column 2 has: 3.  So, data = [1, 4, 2, 3].
From above:
- 1 is from row 1.
- 4 is from row 0.
- 2 is from row 2.
- 3 is from row 2.
- So :  indices = [1, 0, 2, 2]


- indptr: index pointer — tells where each column starts and ends in data i.e. This says where each column starts and ends in the Data Array and  where each column’s values start and stop inside data
- From the earlier example : Column 0 starts at index 0, ends before index 1, Column 1 starts at index 1, ends before index 3 and Column 2 starts at index 3, ends before index 4. So, indptr = [0, 1, 3, 4]



## Examples of CSC.

In [18]:
# Example 1 : Basic Example of CSC.

from scipy.sparse import csc_matrix

dense_matrix = [
    [0, 4, 0],
    [1, 0, 0],
    [0, 2, 3]
]

csc = csc_matrix(dense_matrix)

print("data   :", csc.data)
print("indices:", csc.indices)
print("indptr :", csc.indptr)


data   : [1 4 2 3]
indices: [1 0 2 2]
indptr : [0 1 3 4]


In [19]:
# Example 2 : Basic CSC from Dense.

dense = [[0, 5], [1, 0], [0, 2]]
csc = csc_matrix(dense)
print(csc.toarray())


[[0 5]
 [1 0]
 [0 2]]


In [20]:
# Example 3 : Column Slicing.

print(csc[:, 0].toarray())  # First column



[[0]
 [1]
 [0]]


In [21]:
# Example 4: Scalar Multiplication.

print((csc * 2).toarray())


[[ 0 10]
 [ 2  0]
 [ 0  4]]


In [22]:
# Example 5: Column Vector Multiplication.

vec = np.array([1, 2])
print(csc.dot(vec))


[10  1  4]


In [23]:
# Example 6: Transpose a CSC Matrix.

print(csc.transpose().toarray())


[[0 1 0]
 [5 0 2]]


In [24]:
# Example 7: Convert from CSR.

from scipy.sparse import csr_matrix
csr = csr_matrix([[1, 0], [0, 2]])
csc = csr.tocsc()
print(csc.toarray())


[[1 0]
 [0 2]]


In [25]:
# Example 8: Empty Matrix.

csc = csc_matrix((3, 3))
print(csc.toarray())


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
# Example 9: Duplicate Index Summation.

data = [1, 2]
indices = [0, 0]
indptr = [0, 2]

csc = csc_matrix((data, indices, indptr), shape=(2, 1))
print(csc.toarray())  # Element (0,0) becomes 3


[[3]
 [0]]


## Features of CSC.

## Stores Only Non-Zero Values  :  Like other formats, CSC stores only Non - Zero Elements.

In [27]:
from scipy.sparse import csc_matrix

dense = [[0, 2, 0], [0, 0, 3], [4, 0, 0]]
csc = csc_matrix(dense)
print(csc.toarray())


[[0 2 0]
 [0 0 3]
 [4 0 0]]


## Uses Three Arrays: data, indices, indptr i.e. data: Non - Zero Values,  indices  :  Row Indices and  indptr: column pointer(start of each column in data)



In [28]:
print("Data   :", csc.data)
print("Indices:", csc.indices)
print("IndPtr :", csc.indptr)


Data   : [4 2 3]
Indices: [2 0 1]
IndPtr : [0 1 2 3]


## Efficient for Column Access  :  Column slicing is fast.

In [29]:
print("Column 1:", csc[:, 1].toarray())


Column 1: [[2]
 [0]
 [0]]


## Not Optimized for Row Access  :  Accessing rows is Slower compared to CSR.

In [30]:
print("Row 2:", csc[2].toarray())  # Still possible


Row 2: [[4 0 0]]


## Matrix-Vector Multiplication(Column-wise)  :  CSC is efficient for Column-Based Computations.

In [31]:
import numpy as np
vec = np.array([1, 2, 3])
result = csc.dot(vec)
print("Matrix * Vector =", result)


Matrix * Vector = [4 9 4]
